// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 HoloMUSH Contributors

// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts"
// @generated from file holomush/plugin/v1/attribute.proto (package holomush.plugin.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetSchemaRequest, GetSchemaResponse, ResolveResourceRequest, ResolveResourceResponse } from "./attribute_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * AttributeResolverService is implemented by binary plugins that declare resource_types.
 * The host calls GetSchema once during plugin load to discover attribute schemas,
 * and ResolveResource during ABAC policy evaluation to resolve resource attributes.
 *
 * @generated from service holomush.plugin.v1.AttributeResolverService
 */
export const AttributeResolverService = {
  typeName: "holomush.plugin.v1.AttributeResolverService",
  methods: {
    /**
     * GetSchema returns the attribute schema for resource types this plugin owns.
     * Called once during plugin load.
     *
     * @generated from rpc holomush.plugin.v1.AttributeResolverService.GetSchema
     */
    getSchema: {
      name: "GetSchema",
      I: GetSchemaRequest,
      O: GetSchemaResponse,
      kind: MethodKind.Unary,
    },
    /**
     * ResolveResource returns attributes for a specific resource instance.
     * Called during ABAC policy evaluation.
     *
     * @generated from rpc holomush.plugin.v1.AttributeResolverService.ResolveResource
     */
    resolveResource: {
      name: "ResolveResource",
      I: ResolveResourceRequest,
      O: ResolveResourceResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

