// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 HoloMUSH Contributors

// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file holomush/plugin/v1/audit.proto (package holomush.plugin.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Actor } from "../../eventbus/v1/eventbus_pb";
import { file_holomush_eventbus_v1_eventbus } from "../../eventbus/v1/eventbus_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file holomush/plugin/v1/audit.proto.
 */
export const file_holomush_plugin_v1_audit: GenFile = /*@__PURE__*/
  fileDesc("Ch5ob2xvbXVzaC9wbHVnaW4vdjEvYXVkaXQucHJvdG8SEmhvbG9tdXNoLnBsdWdpbi52MSKQAgoIQXVkaXRSb3cSCgoCaWQYASABKAwSDwoHc3ViamVjdBgCIAEoCRIMCgR0eXBlGAMgASgJEi0KCXRpbWVzdGFtcBgEIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASKgoFYWN0b3IYBSABKAsyGy5ob2xvbXVzaC5ldmVudGJ1cy52MS5BY3RvchINCgVjb2RlYxgGIAEoCRIPCgdwYXlsb2FkGAcgASgMEhQKB2Rla19yZWYYCCABKARIAIgBARIYCgtkZWtfdmVyc2lvbhgJIAEoDUgBiAEBEhIKCnNjaGVtYV92ZXIYCiABKAVCCgoIX2Rla19yZWZCDgoMX2Rla192ZXJzaW9uIj4KEUF1ZGl0RXZlbnRSZXF1ZXN0EikKA3JvdxgBIAEoCzIcLmhvbG9tdXNoLnBsdWdpbi52MS5BdWRpdFJvdyIUChJBdWRpdEV2ZW50UmVzcG9uc2Ui9wEKE1F1ZXJ5SGlzdG9yeVJlcXVlc3QSDwoHc3ViamVjdBgBIAEoCRINCgVhZnRlchgCIAEoDBIOCgZiZWZvcmUYAyABKAwSEQoJcGFnZV9zaXplGAQgASgFEhEKCWRpcmVjdGlvbhgFIAEoBRIuCgpub3RfYmVmb3JlGAYgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBItCglub3RfYWZ0ZXIYByABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wEisKBmNhbGxlchgIIAEoCzIbLmhvbG9tdXNoLmV2ZW50YnVzLnYxLkFjdG9yIkEKFFF1ZXJ5SGlzdG9yeVJlc3BvbnNlEikKA3JvdxgBIAEoCzIcLmhvbG9tdXNoLnBsdWdpbi52MS5BdWRpdFJvdyJIChpEZWNyeXB0T3duQXVkaXRSb3dzUmVxdWVzdBIqCgRyb3dzGAEgAygLMhwuaG9sb211c2gucGx1Z2luLnYxLkF1ZGl0Um93Ik0KG0RlY3J5cHRPd25BdWRpdFJvd3NSZXNwb25zZRIuCgdyZXN1bHRzGAEgAygLMh0uaG9sb211c2gucGx1Z2luLnYxLlJvd1Jlc3VsdCJWCglSb3dSZXN1bHQSCgoCaWQYASABKAwSEwoJcGxhaW50ZXh0GAIgASgMSAASHQoTbm9fcGxhaW50ZXh0X3JlYXNvbhgDIAEoCUgAQgkKB291dGNvbWUy1gEKElBsdWdpbkF1ZGl0U2VydmljZRJbCgpBdWRpdEV2ZW50EiUuaG9sb211c2gucGx1Z2luLnYxLkF1ZGl0RXZlbnRSZXF1ZXN0GiYuaG9sb211c2gucGx1Z2luLnYxLkF1ZGl0RXZlbnRSZXNwb25zZRJjCgxRdWVyeUhpc3RvcnkSJy5ob2xvbXVzaC5wbHVnaW4udjEuUXVlcnlIaXN0b3J5UmVxdWVzdBooLmhvbG9tdXNoLnBsdWdpbi52MS5RdWVyeUhpc3RvcnlSZXNwb25zZTABQkRaQmdpdGh1Yi5jb20vaG9sb211c2gvaG9sb211c2gvcGtnL3Byb3RvL2hvbG9tdXNoL3BsdWdpbi92MTtwbHVnaW52MWIGcHJvdG8z", [file_google_protobuf_timestamp, file_holomush_eventbus_v1_eventbus]);

/**
 * AuditRow is the canonical wire shape for plugin-owned audit rows.
 * Used in both directions: dispatcher → plugin (AuditEventRequest)
 * and plugin → host (QueryHistoryResponse). Mirrors the events_audit
 * row shape so the proto wire format and the storage shape are
 * coupled.
 *
 * @generated from message holomush.plugin.v1.AuditRow
 */
export type AuditRow = Message<"holomush.plugin.v1.AuditRow"> & {
  /**
   * Cleartext projection fields
   *
   * 16-byte ULID
   *
   * @generated from field: bytes id = 1;
   */
  id: Uint8Array;

  /**
   * @generated from field: string subject = 2;
   */
  subject: string;

  /**
   * @generated from field: string type = 3;
   */
  type: string;

  /**
   * @generated from field: google.protobuf.Timestamp timestamp = 4;
   */
  timestamp?: Timestamp | undefined;

  /**
   * @generated from field: holomush.eventbus.v1.Actor actor = 5;
   */
  actor?: Actor | undefined;

  /**
   * Crypto envelope
   *
   * "identity" | "xchacha20poly1305-v1"
   *
   * @generated from field: string codec = 6;
   */
  codec: string;

  /**
   * ciphertext when codec != "identity"
   *
   * @generated from field: bytes payload = 7;
   */
  payload: Uint8Array;

  /**
   * DEK reference — absent on identity codec, required otherwise.
   * Host enforces the agreement (codec=identity ⇔ both absent).
   *
   * @generated from field: optional uint64 dek_ref = 8;
   */
  dekRef?: bigint | undefined;

  /**
   * @generated from field: optional uint32 dek_version = 9;
   */
  dekVersion?: number | undefined;

  /**
   * Audit schema version (was App-Schema-Version header).
   *
   * @generated from field: int32 schema_ver = 10;
   */
  schemaVer: number;
};

/**
 * Describes the message holomush.plugin.v1.AuditRow.
 * Use `create(AuditRowSchema)` to create a new message.
 */
export const AuditRowSchema: GenMessage<AuditRow> = /*@__PURE__*/
  messageDesc(file_holomush_plugin_v1_audit, 0);

/**
 * @generated from message holomush.plugin.v1.AuditEventRequest
 */
export type AuditEventRequest = Message<"holomush.plugin.v1.AuditEventRequest"> & {
  /**
   * @generated from field: holomush.plugin.v1.AuditRow row = 1;
   */
  row?: AuditRow | undefined;
};

/**
 * Describes the message holomush.plugin.v1.AuditEventRequest.
 * Use `create(AuditEventRequestSchema)` to create a new message.
 */
export const AuditEventRequestSchema: GenMessage<AuditEventRequest> = /*@__PURE__*/
  messageDesc(file_holomush_plugin_v1_audit, 1);

/**
 * @generated from message holomush.plugin.v1.AuditEventResponse
 */
export type AuditEventResponse = Message<"holomush.plugin.v1.AuditEventResponse"> & {
};

/**
 * Describes the message holomush.plugin.v1.AuditEventResponse.
 * Use `create(AuditEventResponseSchema)` to create a new message.
 */
export const AuditEventResponseSchema: GenMessage<AuditEventResponse> = /*@__PURE__*/
  messageDesc(file_holomush_plugin_v1_audit, 2);

/**
 * @generated from message holomush.plugin.v1.QueryHistoryRequest
 */
export type QueryHistoryRequest = Message<"holomush.plugin.v1.QueryHistoryRequest"> & {
  /**
   * @generated from field: string subject = 1;
   */
  subject: string;

  /**
   * ULID; empty = from start
   *
   * @generated from field: bytes after = 2;
   */
  after: Uint8Array;

  /**
   * ULID; empty = unbounded
   *
   * @generated from field: bytes before = 3;
   */
  before: Uint8Array;

  /**
   * host caps at 200
   *
   * @generated from field: int32 page_size = 4;
   */
  pageSize: number;

  /**
   * 1=forward, 2=backward
   *
   * @generated from field: int32 direction = 5;
   */
  direction: number;

  /**
   * @generated from field: google.protobuf.Timestamp not_before = 6;
   */
  notBefore?: Timestamp | undefined;

  /**
   * @generated from field: google.protobuf.Timestamp not_after = 7;
   */
  notAfter?: Timestamp | undefined;

  /**
   * caller identifies the principal on whose behalf the host is reading.
   * Plugins implementing PluginAuditService MUST enforce domain-specific
   * authz (e.g., membership) against this identity before returning rows.
   * An absent caller, a zero identity, or an unsupported Actor.Kind MUST
   * be rejected with gRPC PERMISSION_DENIED. The host populates this
   * field from the authenticated session record; clients never supply it.
   *
   * @generated from field: holomush.eventbus.v1.Actor caller = 8;
   */
  caller?: Actor | undefined;
};

/**
 * Describes the message holomush.plugin.v1.QueryHistoryRequest.
 * Use `create(QueryHistoryRequestSchema)` to create a new message.
 */
export const QueryHistoryRequestSchema: GenMessage<QueryHistoryRequest> = /*@__PURE__*/
  messageDesc(file_holomush_plugin_v1_audit, 3);

/**
 * @generated from message holomush.plugin.v1.QueryHistoryResponse
 */
export type QueryHistoryResponse = Message<"holomush.plugin.v1.QueryHistoryResponse"> & {
  /**
   * @generated from field: holomush.plugin.v1.AuditRow row = 1;
   */
  row?: AuditRow | undefined;
};

/**
 * Describes the message holomush.plugin.v1.QueryHistoryResponse.
 * Use `create(QueryHistoryResponseSchema)` to create a new message.
 */
export const QueryHistoryResponseSchema: GenMessage<QueryHistoryResponse> = /*@__PURE__*/
  messageDesc(file_holomush_plugin_v1_audit, 4);

/**
 * DecryptOwnAuditRowsRequest carries the calling plugin's OWN audit rows for
 * host-side read-back decryption (PluginHostService.DecryptOwnAuditRows).
 * The host enforces OwnerMap subject ownership (g1) per row; rows whose
 * subject is owned by a different plugin are refused with not_owner and never
 * decrypted. The batch is REJECTED (not clamped) when it exceeds the
 * server-side cap of 500.
 *
 * @generated from message holomush.plugin.v1.DecryptOwnAuditRowsRequest
 */
export type DecryptOwnAuditRowsRequest = Message<"holomush.plugin.v1.DecryptOwnAuditRowsRequest"> & {
  /**
   * @generated from field: repeated holomush.plugin.v1.AuditRow rows = 1;
   */
  rows: AuditRow[];
};

/**
 * Describes the message holomush.plugin.v1.DecryptOwnAuditRowsRequest.
 * Use `create(DecryptOwnAuditRowsRequestSchema)` to create a new message.
 */
export const DecryptOwnAuditRowsRequestSchema: GenMessage<DecryptOwnAuditRowsRequest> = /*@__PURE__*/
  messageDesc(file_holomush_plugin_v1_audit, 5);

/**
 * DecryptOwnAuditRowsResponse returns one RowResult per request row, in the
 * same order (1:1 positional correspondence, INV-RB-12).
 *
 * @generated from message holomush.plugin.v1.DecryptOwnAuditRowsResponse
 */
export type DecryptOwnAuditRowsResponse = Message<"holomush.plugin.v1.DecryptOwnAuditRowsResponse"> & {
  /**
   * @generated from field: repeated holomush.plugin.v1.RowResult results = 1;
   */
  results: RowResult[];
};

/**
 * Describes the message holomush.plugin.v1.DecryptOwnAuditRowsResponse.
 * Use `create(DecryptOwnAuditRowsResponseSchema)` to create a new message.
 */
export const DecryptOwnAuditRowsResponseSchema: GenMessage<DecryptOwnAuditRowsResponse> = /*@__PURE__*/
  messageDesc(file_holomush_plugin_v1_audit, 6);

/**
 * RowResult is the per-row outcome of DecryptOwnAuditRows. Exactly one of
 * plaintext / no_plaintext_reason is populated: plaintext is set iff the row
 * decrypted; no_plaintext_reason is set iff the row was refused (e.g.
 * "not_owner", "downgrade_refused", "dek_missing", "internal").
 *
 * @generated from message holomush.plugin.v1.RowResult
 */
export type RowResult = Message<"holomush.plugin.v1.RowResult"> & {
  /**
   * echoes AuditRow.id for correlation
   *
   * @generated from field: bytes id = 1;
   */
  id: Uint8Array;

  /**
   * Exactly one outcome arm is set: plaintext iff the row decrypted,
   * no_plaintext_reason iff it was refused. The oneof makes both-set /
   * neither-set unrepresentable and distinguishes decrypted-to-empty from refused.
   *
   * @generated from oneof holomush.plugin.v1.RowResult.outcome
   */
  outcome: {
    /**
     * set iff decrypted
     *
     * @generated from field: bytes plaintext = 2;
     */
    value: Uint8Array;
    case: "plaintext";
  } | {
    /**
     * set iff refused
     *
     * @generated from field: string no_plaintext_reason = 3;
     */
    value: string;
    case: "noPlaintextReason";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message holomush.plugin.v1.RowResult.
 * Use `create(RowResultSchema)` to create a new message.
 */
export const RowResultSchema: GenMessage<RowResult> = /*@__PURE__*/
  messageDesc(file_holomush_plugin_v1_audit, 7);

/**
 * PluginAuditService is implemented by plugins that declare audit
 * subjects in their manifest. The host owns the JetStream durable
 * consumer and forwards each delivered event to the plugin via
 * AuditEvent. The plugin INSERTs into its own schema and acks.
 *
 * QueryHistory is invoked by host's bus.QueryHistory when the queried
 * subject prefix is owned by this plugin.
 *
 * @generated from service holomush.plugin.v1.PluginAuditService
 */
export const PluginAuditService: GenService<{
  /**
   * @generated from rpc holomush.plugin.v1.PluginAuditService.AuditEvent
   */
  auditEvent: {
    methodKind: "unary";
    input: typeof AuditEventRequestSchema;
    output: typeof AuditEventResponseSchema;
  },
  /**
   * @generated from rpc holomush.plugin.v1.PluginAuditService.QueryHistory
   */
  queryHistory: {
    methodKind: "server_streaming";
    input: typeof QueryHistoryRequestSchema;
    output: typeof QueryHistoryResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_holomush_plugin_v1_audit, 0);

