// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 HoloMUSH Contributors

// api/proto/holomush/plugin/v1/hostfunc.proto

// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts"
// @generated from file holomush/plugin/v1/hostfunc.proto (package holomush.plugin.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { EmitEventRequest, EmitEventResponse, GetCommandHelpRequest, GetCommandHelpResponse, KVDeleteRequest, KVDeleteResponse, KVGetRequest, KVGetResponse, KVSetRequest, KVSetResponse, ListCommandsRequest, ListCommandsResponse, LogRequest, LogResponse, QueryCharacterRequest, QueryCharacterResponse, QueryRoomCharactersRequest, QueryRoomCharactersResponse, QueryRoomRequest, QueryRoomResponse } from "./hostfunc_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * HostFunctions service provides host capabilities to plugins.
 * This service is implemented by the host (the gRPC server runs in the host process).
 * Plugins call these methods to interact with the game world.
 *
 * @generated from service holomush.plugin.v1.HostFunctions
 */
export const HostFunctions = {
  typeName: "holomush.plugin.v1.HostFunctions",
  methods: {
    /**
     * EmitEvent publishes an event to a stream.
     *
     * @generated from rpc holomush.plugin.v1.HostFunctions.EmitEvent
     */
    emitEvent: {
      name: "EmitEvent",
      I: EmitEventRequest,
      O: EmitEventResponse,
      kind: MethodKind.Unary,
    },
    /**
     * QueryRoom retrieves information about a room.
     *
     * @generated from rpc holomush.plugin.v1.HostFunctions.QueryRoom
     */
    queryRoom: {
      name: "QueryRoom",
      I: QueryRoomRequest,
      O: QueryRoomResponse,
      kind: MethodKind.Unary,
    },
    /**
     * QueryCharacter retrieves information about a character.
     *
     * @generated from rpc holomush.plugin.v1.HostFunctions.QueryCharacter
     */
    queryCharacter: {
      name: "QueryCharacter",
      I: QueryCharacterRequest,
      O: QueryCharacterResponse,
      kind: MethodKind.Unary,
    },
    /**
     * QueryRoomCharacters retrieves all characters in a room.
     *
     * @generated from rpc holomush.plugin.v1.HostFunctions.QueryRoomCharacters
     */
    queryRoomCharacters: {
      name: "QueryRoomCharacters",
      I: QueryRoomCharactersRequest,
      O: QueryRoomCharactersResponse,
      kind: MethodKind.Unary,
    },
    /**
     * KVGet retrieves a value from the plugin's key-value store.
     *
     * @generated from rpc holomush.plugin.v1.HostFunctions.KVGet
     */
    kVGet: {
      name: "KVGet",
      I: KVGetRequest,
      O: KVGetResponse,
      kind: MethodKind.Unary,
    },
    /**
     * KVSet stores a value in the plugin's key-value store.
     *
     * @generated from rpc holomush.plugin.v1.HostFunctions.KVSet
     */
    kVSet: {
      name: "KVSet",
      I: KVSetRequest,
      O: KVSetResponse,
      kind: MethodKind.Unary,
    },
    /**
     * KVDelete removes a value from the plugin's key-value store.
     *
     * @generated from rpc holomush.plugin.v1.HostFunctions.KVDelete
     */
    kVDelete: {
      name: "KVDelete",
      I: KVDeleteRequest,
      O: KVDeleteResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Log writes a log message through the host's logging system.
     *
     * @generated from rpc holomush.plugin.v1.HostFunctions.Log
     */
    log: {
      name: "Log",
      I: LogRequest,
      O: LogResponse,
      kind: MethodKind.Unary,
    },
    /**
     * ListCommands returns all available commands.
     * Requires capability: command.list
     *
     * @generated from rpc holomush.plugin.v1.HostFunctions.ListCommands
     */
    listCommands: {
      name: "ListCommands",
      I: ListCommandsRequest,
      O: ListCommandsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * GetCommandHelp returns detailed help for a specific command.
     * Requires capability: command.help
     *
     * @generated from rpc holomush.plugin.v1.HostFunctions.GetCommandHelp
     */
    getCommandHelp: {
      name: "GetCommandHelp",
      I: GetCommandHelpRequest,
      O: GetCommandHelpResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

