// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 HoloMUSH Contributors

// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file holomush/eventbus/v1/eventbus.proto (package holomush.eventbus.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { RenderingMetadata } from "../../core/v1/core_pb";
import { file_holomush_core_v1_core } from "../../core/v1/core_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file holomush/eventbus/v1/eventbus.proto.
 */
export const file_holomush_eventbus_v1_eventbus: GenFile = /*@__PURE__*/
  fileDesc("CiNob2xvbXVzaC9ldmVudGJ1cy92MS9ldmVudGJ1cy5wcm90bxIUaG9sb211c2guZXZlbnRidXMudjEiUwoFQWN0b3ISLQoEa2luZBgBIAEoDjIfLmhvbG9tdXNoLmV2ZW50YnVzLnYxLkFjdG9yS2luZBIKCgJpZBgCIAEoDEoECAMQBFIJbGVnYWN5X2lkItYBCgVFdmVudBIKCgJpZBgBIAEoDBIPCgdzdWJqZWN0GAIgASgJEgwKBHR5cGUYAyABKAkSLQoJdGltZXN0YW1wGAQgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBIqCgVhY3RvchgFIAEoCzIbLmhvbG9tdXNoLmV2ZW50YnVzLnYxLkFjdG9yEg8KB3BheWxvYWQYBiABKAwSNgoJcmVuZGVyaW5nGAcgASgLMiMuaG9sb211c2guY29yZS52MS5SZW5kZXJpbmdNZXRhZGF0YSqGAQoJQWN0b3JLaW5kEhoKFkFDVE9SX0tJTkRfVU5TUEVDSUZJRUQQABIYChRBQ1RPUl9LSU5EX0NIQVJBQ1RFUhABEhUKEUFDVE9SX0tJTkRfUExBWUVSEAISFQoRQUNUT1JfS0lORF9TWVNURU0QAxIVChFBQ1RPUl9LSU5EX1BMVUdJThAEQkhaRmdpdGh1Yi5jb20vaG9sb211c2gvaG9sb211c2gvcGtnL3Byb3RvL2hvbG9tdXNoL2V2ZW50YnVzL3YxO2V2ZW50YnVzdjFiBnByb3RvMw", [file_google_protobuf_timestamp, file_holomush_core_v1_core]);

/**
 * Actor identifies who caused an event.
 *
 * @generated from message holomush.eventbus.v1.Actor
 */
export type Actor = Message<"holomush.eventbus.v1.Actor"> & {
  /**
   * @generated from field: holomush.eventbus.v1.ActorKind kind = 1;
   */
  kind: ActorKind;

  /**
   * ULID (16 bytes); MUST be set for every ActorKind value.
   *
   * @generated from field: bytes id = 2;
   */
  id: Uint8Array;
};

/**
 * Describes the message holomush.eventbus.v1.Actor.
 * Use `create(ActorSchema)` to create a new message.
 */
export const ActorSchema: GenMessage<Actor> = /*@__PURE__*/
  messageDesc(file_holomush_eventbus_v1_eventbus, 0);

/**
 * Event is the host-side envelope. Wire encoding is proto bytes in the
 * JetStream message data; headers carry routing/codec/version metadata.
 *
 * @generated from message holomush.eventbus.v1.Event
 */
export type Event = Message<"holomush.eventbus.v1.Event"> & {
  /**
   * ULID (16 bytes)
   *
   * @generated from field: bytes id = 1;
   */
  id: Uint8Array;

  /**
   * @generated from field: string subject = 2;
   */
  subject: string;

  /**
   * @generated from field: string type = 3;
   */
  type: string;

  /**
   * @generated from field: google.protobuf.Timestamp timestamp = 4;
   */
  timestamp?: Timestamp | undefined;

  /**
   * @generated from field: holomush.eventbus.v1.Actor actor = 5;
   */
  actor?: Actor | undefined;

  /**
   * codec.Encode output
   *
   * @generated from field: bytes payload = 6;
   */
  payload: Uint8Array;

  /**
   * Rendering metadata, populated by RenderingPublisher.Publish before
   * marshaling for JetStream. Mirrors the corev1.RenderingMetadata used
   * on the gRPC Subscribe wire (one schema, two transports).
   *
   * @generated from field: holomush.core.v1.RenderingMetadata rendering = 7;
   */
  rendering?: RenderingMetadata | undefined;
};

/**
 * Describes the message holomush.eventbus.v1.Event.
 * Use `create(EventSchema)` to create a new message.
 */
export const EventSchema: GenMessage<Event> = /*@__PURE__*/
  messageDesc(file_holomush_eventbus_v1_eventbus, 1);

/**
 * ActorKind identifies what type of entity caused an event.
 *
 * @generated from enum holomush.eventbus.v1.ActorKind
 */
export enum ActorKind {
  /**
   * @generated from enum value: ACTOR_KIND_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: ACTOR_KIND_CHARACTER = 1;
   */
  CHARACTER = 1,

  /**
   * @generated from enum value: ACTOR_KIND_PLAYER = 2;
   */
  PLAYER = 2,

  /**
   * @generated from enum value: ACTOR_KIND_SYSTEM = 3;
   */
  SYSTEM = 3,

  /**
   * @generated from enum value: ACTOR_KIND_PLUGIN = 4;
   */
  PLUGIN = 4,
}

/**
 * Describes the enum holomush.eventbus.v1.ActorKind.
 */
export const ActorKindSchema: GenEnum<ActorKind> = /*@__PURE__*/
  enumDesc(file_holomush_eventbus_v1_eventbus, 0);

