// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 HoloMUSH Contributors

// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// MockGuestTransactor is an autogenerated mock type for the GuestTransactor type
type MockGuestTransactor struct {
	mock.Mock
}

type MockGuestTransactor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGuestTransactor) EXPECT() *MockGuestTransactor_Expecter {
	return &MockGuestTransactor_Expecter{mock: &_m.Mock}
}

// InTransaction provides a mock function with given fields: ctx, fn
func (_m *MockGuestTransactor) InTransaction(ctx context.Context, fn func(context.Context) error) error {
	ret := _m.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for InTransaction")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, func(context.Context) error) error); ok {
		r0 = rf(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGuestTransactor_InTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InTransaction'
type MockGuestTransactor_InTransaction_Call struct {
	*mock.Call
}

// InTransaction is a helper method to define mock.On call
//   - ctx context.Context
//   - fn func(context.Context) error
func (_e *MockGuestTransactor_Expecter) InTransaction(ctx interface{}, fn interface{}) *MockGuestTransactor_InTransaction_Call {
	return &MockGuestTransactor_InTransaction_Call{Call: _e.mock.On("InTransaction", ctx, fn)}
}

func (_c *MockGuestTransactor_InTransaction_Call) Run(run func(ctx context.Context, fn func(context.Context) error)) *MockGuestTransactor_InTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(func(context.Context) error))
	})
	return _c
}

func (_c *MockGuestTransactor_InTransaction_Call) Return(_a0 error) *MockGuestTransactor_InTransaction_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGuestTransactor_InTransaction_Call) RunAndReturn(run func(context.Context, func(context.Context) error) error) *MockGuestTransactor_InTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGuestTransactor creates a new instance of MockGuestTransactor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGuestTransactor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGuestTransactor {
	mock := &MockGuestTransactor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
