// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 HoloMUSH Contributors

// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	ulid "github.com/oklog/ulid/v2"
	mock "github.com/stretchr/testify/mock"
)

// MockGuestCharacterRepository is an autogenerated mock type for the GuestCharacterRepository type
type MockGuestCharacterRepository struct {
	mock.Mock
}

type MockGuestCharacterRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGuestCharacterRepository) EXPECT() *MockGuestCharacterRepository_Expecter {
	return &MockGuestCharacterRepository_Expecter{mock: &_m.Mock}
}

// ExistsByNormalizedName provides a mock function with given fields: ctx, key, excluding
func (_m *MockGuestCharacterRepository) ExistsByNormalizedName(ctx context.Context, key string, excluding *ulid.ULID) (bool, error) {
	ret := _m.Called(ctx, key, excluding)

	if len(ret) == 0 {
		panic("no return value specified for ExistsByNormalizedName")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *ulid.ULID) (bool, error)); ok {
		return rf(ctx, key, excluding)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *ulid.ULID) bool); ok {
		r0 = rf(ctx, key, excluding)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *ulid.ULID) error); ok {
		r1 = rf(ctx, key, excluding)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGuestCharacterRepository_ExistsByNormalizedName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExistsByNormalizedName'
type MockGuestCharacterRepository_ExistsByNormalizedName_Call struct {
	*mock.Call
}

// ExistsByNormalizedName is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - excluding *ulid.ULID
func (_e *MockGuestCharacterRepository_Expecter) ExistsByNormalizedName(ctx interface{}, key interface{}, excluding interface{}) *MockGuestCharacterRepository_ExistsByNormalizedName_Call {
	return &MockGuestCharacterRepository_ExistsByNormalizedName_Call{Call: _e.mock.On("ExistsByNormalizedName", ctx, key, excluding)}
}

func (_c *MockGuestCharacterRepository_ExistsByNormalizedName_Call) Run(run func(ctx context.Context, key string, excluding *ulid.ULID)) *MockGuestCharacterRepository_ExistsByNormalizedName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*ulid.ULID))
	})
	return _c
}

func (_c *MockGuestCharacterRepository_ExistsByNormalizedName_Call) Return(_a0 bool, _a1 error) *MockGuestCharacterRepository_ExistsByNormalizedName_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGuestCharacterRepository_ExistsByNormalizedName_Call) RunAndReturn(run func(context.Context, string, *ulid.ULID) (bool, error)) *MockGuestCharacterRepository_ExistsByNormalizedName_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGuestCharacterRepository creates a new instance of MockGuestCharacterRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGuestCharacterRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGuestCharacterRepository {
	mock := &MockGuestCharacterRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
