run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    # Bugs
    - errcheck
    - govet
    - staticcheck
    - nilerr

    # Style
    - revive
    - gofumpt
    - misspell

    # Performance
    - prealloc
    - unconvert

    # Security
    - gosec

    # Error handling
    - errorlint
    - wrapcheck

    # Maintenance
    - unparam
    - gocritic
    - nolintlint

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    enable-all: true

  revive:
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unused-parameter
      - name: unreachable-code
      - name: redefines-builtin-id

  gofumpt:
    extra-rules: true

  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance

  gosec:
    excludes:
      - G104 # Audit errors not checked (handled by errcheck)

  wrapcheck:
    ignoreSigs:
      - .Errorf(
      - errors.New(
      - errors.Unwrap(
      - errors.Join(
      - .Wrap(
      - .Wrapf(
      - .WithMessage(
      - .WithMessagef(
      - .WithStack(

  nolintlint:
    require-explanation: true
    require-specific: true

issues:
  exclude-rules:
    # Test files can have longer functions and more complexity
    - path: _test\.go
      linters:
        - gocritic
        - wrapcheck

    # Main package doesn't need to wrap errors
    - path: cmd/
      linters:
        - wrapcheck

  max-issues-per-linter: 0
  max-same-issues: 0
