# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 HoloMUSH Contributors

# goreleaser configuration
# https://goreleaser.com

version: 2

project_name: holomush

before:
  hooks:
    - go mod tidy

builds:
  - id: holomush
    main: ./cmd/holomush
    binary: holomush
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: default
    formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "checksums.txt"

# SBOM generation - separate entries for each format (syft generates one format per run)
sboms:
  - id: binary-sbom-cyclonedx
    artifacts: archive
    documents:
      - "{{ .ArtifactName }}.sbom.cyclonedx.json"
    args: ["$artifact", "--output", "cyclonedx-json=$document"]

  - id: binary-sbom-spdx
    artifacts: archive
    documents:
      - "{{ .ArtifactName }}.sbom.spdx.json"
    args: ["$artifact", "--output", "spdx-json=$document"]

  - id: source-sbom-cyclonedx
    artifacts: source
    documents:
      - "{{ .ProjectName }}_{{ .Version }}_source.sbom.cyclonedx.json"
    args: ["$artifact", "--output", "cyclonedx-json=$document"]

  - id: source-sbom-spdx
    artifacts: source
    documents:
      - "{{ .ProjectName }}_{{ .Version }}_source.sbom.spdx.json"
    args: ["$artifact", "--output", "spdx-json=$document"]

# Keyless signing with Cosign (uses GitHub Actions OIDC)
# Signing happens BEFORE release publication - artifacts are never published unsigned
signs:
  - cmd: cosign
    artifacts: checksum
    output: true
    args:
      - "sign-blob"
      - "--output-signature=${signature}"
      - "--output-certificate=${signature}.cert"
      - "${artifact}"
      - "--yes"

# Sign container images with Cosign keyless signing
docker_signs:
  - cmd: cosign
    artifacts: manifests
    output: true
    args:
      - "sign"
      - "${artifact}"
      - "--yes"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "Merge pull request"
      - "Merge branch"

dockers:
  - image_templates:
      - "ghcr.io/holomush/holomush:{{ .Version }}-amd64"
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.source={{ .GitURL }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
    dockerfile: Dockerfile
    goos: linux
    goarch: amd64

  - image_templates:
      - "ghcr.io/holomush/holomush:{{ .Version }}-arm64"
    use: buildx
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.source={{ .GitURL }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
    dockerfile: Dockerfile
    goos: linux
    goarch: arm64

docker_manifests:
  - name_template: "ghcr.io/holomush/holomush:{{ .Version }}"
    image_templates:
      - "ghcr.io/holomush/holomush:{{ .Version }}-amd64"
      - "ghcr.io/holomush/holomush:{{ .Version }}-arm64"

  - name_template: "ghcr.io/holomush/holomush:latest"
    image_templates:
      - "ghcr.io/holomush/holomush:{{ .Version }}-amd64"
      - "ghcr.io/holomush/holomush:{{ .Version }}-arm64"

release:
  github:
    owner: holomush
    name: holomush
  draft: false
  prerelease: auto
