# goreleaser configuration
# https://goreleaser.com

version: 2

project_name: holomush

before:
  hooks:
    - go mod tidy

builds:
  - id: holomush
    main: ./cmd/holomush
    binary: holomush
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: default
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "Merge pull request"
      - "Merge branch"

dockers:
  - image_templates:
      - "ghcr.io/holomush/holomush:{{ .Version }}-amd64"
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.source={{ .GitURL }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
    dockerfile: Dockerfile
    goos: linux
    goarch: amd64

  - image_templates:
      - "ghcr.io/holomush/holomush:{{ .Version }}-arm64"
    use: buildx
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.source={{ .GitURL }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
    dockerfile: Dockerfile
    goos: linux
    goarch: arm64

docker_manifests:
  - name_template: "ghcr.io/holomush/holomush:{{ .Version }}"
    image_templates:
      - "ghcr.io/holomush/holomush:{{ .Version }}-amd64"
      - "ghcr.io/holomush/holomush:{{ .Version }}-arm64"

  - name_template: "ghcr.io/holomush/holomush:latest"
    image_templates:
      - "ghcr.io/holomush/holomush:{{ .Version }}-amd64"
      - "ghcr.io/holomush/holomush:{{ .Version }}-arm64"

release:
  github:
    owner: holomush
    name: holomush
  draft: false
  prerelease: auto
