# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 HoloMUSH Contributors

boilerplate-file: .mockery-boilerplate.txt
with-expecter: true
resolve-type-alias: false
disable-version-string: true
issue-845-fix: true
packages:
  github.com/holomush/holomush/internal/core:
    config:
      dir: "{{.InterfaceDir}}/mocks"
      outpkg: mocks
    interfaces:
      EventStore:
  github.com/holomush/holomush/internal/grpc:
    config:
      dir: "{{.InterfaceDir}}/mocks"
      outpkg: mocks
    interfaces:
      AuthServiceProvider:
      ResetServiceProvider:
      CharacterServiceProvider:
  github.com/holomush/holomush/internal/plugin:
    config:
      dir: "{{.InterfaceDir}}/mocks"
      outpkg: mocks
    interfaces:
      Host:
      EventEmitter:
      ServiceProxy:
  github.com/holomush/holomush/internal/plugin/hostfunc:
    config:
      dir: "{{.InterfaceDir}}/mocks"
      outpkg: mocks
    interfaces:
      KVStore:
  github.com/holomush/holomush/internal/world:
    config:
      dir: internal/world/worldtest
      outpkg: worldtest
    interfaces:
      LocationRepository:
      ExitRepository:
      ObjectRepository:
      SceneRepository:
      CharacterRepository:
      PropertyRepository:
  github.com/holomush/holomush/internal/access/policy/types:
    config:
      dir: internal/access/policy/policytest
      outpkg: policytest
    interfaces:
      AccessPolicyEngine:
  github.com/holomush/holomush/internal/eventbus/crypto/kek:
    config:
      dir: "{{.InterfaceDir}}/mocks"
      outpkg: mocks
    interfaces:
      Provider:
  github.com/holomush/holomush/internal/command:
    config:
      dir: "{{.InterfaceDir}}/mocks"
      outpkg: mocks
    interfaces:
      AliasWriter:
  github.com/holomush/holomush/internal/auth:
    config:
      dir: "{{.InterfaceDir}}/mocks"
      outpkg: mocks
    interfaces:
      PasswordHasher:
      PlayerRepository:
      PasswordResetRepository:
      CharacterRepository:
      LocationRepository:
      PlayerSessionRepository:
      GuestNamer:
      GuestCharacterRepository:
  github.com/holomush/holomush/internal/session:
    config:
      dir: "{{.InterfaceDir}}/mocks"
      outpkg: mocks
    interfaces:
      Store:
  github.com/holomush/holomush/internal/totp:
    config:
      dir: "{{.InterfaceDir}}/mocks"
      outpkg: mocks
    interfaces:
      Repository:
      RecoveryCodeHasher:
  github.com/holomush/holomush/pkg/proto/holomush/scene/v1:
    config:
      dir: internal/grpc/scenemocks
      outpkg: scenemocks
    interfaces:
      SceneServiceClient:
