# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 HoloMUSH Contributors

with-expecter: true
resolve-type-alias: false
disable-version-string: true
issue-845-fix: true
packages:
  github.com/holomush/holomush/internal/core:
    config:
      dir: "{{.InterfaceDir}}/mocks"
      outpkg: mocks
    interfaces:
      EventStore:
  github.com/holomush/holomush/internal/grpc:
    config:
      dir: "{{.InterfaceDir}}/mocks"
      outpkg: mocks
    interfaces:
      Authenticator:
      SessionStore:
  github.com/holomush/holomush/internal/plugin:
    config:
      dir: "{{.InterfaceDir}}/mocks"
      outpkg: mocks
    interfaces:
      Host:
      EventEmitter:
  github.com/holomush/holomush/internal/plugin/hostfunc:
    config:
      dir: "{{.InterfaceDir}}/mocks"
      outpkg: mocks
    interfaces:
      KVStore:
      CapabilityChecker:
  github.com/holomush/holomush/internal/world:
    config:
      dir: internal/world/worldtest
      outpkg: worldtest
    interfaces:
      LocationRepository:
      ExitRepository:
      ObjectRepository:
      SceneRepository:
