# yamllint configuration
# https://yamllint.readthedocs.io/

extends: default

rules:
  # Line length - allow longer lines for URLs and such
  line-length:
    max: 120
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: true

  # Indentation
  indentation:
    spaces: 2
    indent-sequences: true

  # Braces
  braces:
    min-spaces-inside: 0
    max-spaces-inside: 1

  # Brackets
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 0

  # Comments
  comments:
    require-starting-space: true
    min-spaces-from-content: 1

  # Document markers
  document-start: disable

  # Truthy values
  truthy:
    allowed-values:
      - "true"
      - "false"
      - "on"
      - "off"
