# https://taskfile.dev

version: "3"

vars:
  BINARY_NAME: holomush
  MAIN_PKG: ./cmd/holomush

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  # Development
  dev:
    desc: Run server in development mode
    cmds:
      - go run {{.MAIN_PKG}}

  # Building
  build:
    desc: Build the server binary
    cmds:
      - go build -o {{.BINARY_NAME}} {{.MAIN_PKG}}

  build:all:
    desc: Build for all platforms
    cmds:
      - task: build:linux
      - task: build:darwin

  build:linux:
    desc: Build for Linux
    cmds:
      - GOOS=linux GOARCH=amd64 go build -o dist/{{.BINARY_NAME}}-linux-amd64 {{.MAIN_PKG}}
      - GOOS=linux GOARCH=arm64 go build -o dist/{{.BINARY_NAME}}-linux-arm64 {{.MAIN_PKG}}

  build:darwin:
    desc: Build for macOS
    cmds:
      - GOOS=darwin GOARCH=amd64 go build -o dist/{{.BINARY_NAME}}-darwin-amd64 {{.MAIN_PKG}}
      - GOOS=darwin GOARCH=arm64 go build -o dist/{{.BINARY_NAME}}-darwin-arm64 {{.MAIN_PKG}}

  # Proto generation
  proto:
    desc: Generate Go code from protobuf definitions
    cmds:
      - buf generate
    sources:
      - api/proto/**/*.proto
      - buf.yaml
      - buf.gen.yaml
    generates:
      - internal/proto/**/*.go

  # Testing
  test:
    desc: Run all tests
    deps:
      - plugin:build
    cmds:
      - go test -race -v ./...

  test:coverage:
    desc: Run tests with coverage
    deps:
      - plugin:build
    cmds:
      - go test -race -coverprofile=coverage.out -covermode=atomic ./...
      - go tool cover -html=coverage.out -o coverage.html

  test:short:
    desc: Run short tests only
    cmds:
      - go test -short -v ./...

  test:integration:
    desc: Run integration tests (requires Docker)
    deps:
      - plugin:build
    cmds:
      - go test -race -v -tags=integration ./...

  # Linting
  lint:
    desc: Run all linters
    cmds:
      - task: lint:go
      - task: lint:markdown
      - task: lint:yaml
      - task: lint:actions

  lint:go:
    desc: Lint Go code
    cmds:
      - golangci-lint run

  lint:markdown:
    desc: Lint Markdown files
    cmds:
      - markdownlint-cli2 "**/*.md" "#node_modules" "#vendor" "#.beads" "#.git" "#.worktrees" "#dist" "#.claude"

  lint:yaml:
    desc: Lint YAML files
    cmds:
      - uvx yamllint .

  lint:actions:
    desc: Lint GitHub Actions workflows
    cmds:
      - actionlint

  # Formatting
  fmt:
    desc: Format all files
    cmds:
      - task: fmt:go
      - task: fmt:dprint

  fmt:go:
    desc: Format Go code
    cmds:
      - gofumpt -w .

  fmt:dprint:
    desc: Format with dprint
    cmds:
      - dprint fmt

  fmt:check:
    desc: Check formatting without modifying
    cmds:
      - dprint check

  # Dependencies
  deps:
    desc: Download and tidy dependencies
    cmds:
      - go mod download
      - go mod tidy

  deps:upgrade:
    desc: Upgrade all dependencies
    cmds:
      - go get -u ./...
      - go mod tidy

  # Plugins
  plugin:build:
    desc: Build all WASM plugins (production only)
    cmds:
      - task: plugin:build:echo-python

  plugin:build:echo-python:
    desc: Build Python echo plugin to WASM
    dir: plugins/echo-python
    cmds:
      - extism-py plugin.py -o echo.wasm
      - cp echo.wasm ../../internal/wasm/testdata/echo.wasm
    sources:
      - plugin.py
    generates:
      - echo.wasm
      - ../../internal/wasm/testdata/echo.wasm

  # Test fixtures (not for production use)
  test:fixtures:build:
    desc: Build test fixture plugins (for testing error handling)
    cmds:
      - task: test:fixtures:build:malformed-json
      - task: test:fixtures:build:empty-stream

  test:fixtures:build:malformed-json:
    desc: Build malformed JSON test fixture
    dir: test/fixtures/plugins/malformed-json
    cmds:
      - extism-py plugin.py -o malformed.wasm
      - cp malformed.wasm ../../../../internal/wasm/testdata/malformed.wasm
    sources:
      - plugin.py
    generates:
      - malformed.wasm
      - ../../../../internal/wasm/testdata/malformed.wasm

  test:fixtures:build:empty-stream:
    desc: Build empty-stream test fixture
    dir: test/fixtures/plugins/empty-stream
    cmds:
      - extism-py plugin.py -o empty-stream.wasm
      - cp empty-stream.wasm ../../../../internal/wasm/testdata/empty-stream.wasm
    sources:
      - plugin.py
    generates:
      - empty-stream.wasm
      - ../../../../internal/wasm/testdata/empty-stream.wasm

  # Documentation
  spec:
    desc: Create a new spec document
    cmds:
      - |
          DATE=$(date +%Y-%m-%d)
          read -p "Spec name (e.g., event-system): " NAME
          FILE="docs/specs/${DATE}-${NAME}.md"
          cat > "$FILE" << 'EOF'
          # {{.NAME}} Specification

          **Status:** Draft
          **Date:** {{.DATE}}
          **Version:** 0.1.0

          ## Overview

          ## Requirements

          ## Non-Goals

          ## Design

          ## Open Questions
          EOF
          echo "Created: $FILE"

  plan:
    desc: Create a new plan document
    cmds:
      - |
          DATE=$(date +%Y-%m-%d)
          read -p "Plan name (e.g., phase-1-implementation): " NAME
          FILE="docs/plans/${DATE}-${NAME}.md"
          cat > "$FILE" << 'EOF'
          # {{.NAME}} Plan

          **Status:** Draft
          **Date:** {{.DATE}}

          ## Overview

          ## Tasks

          ## Dependencies

          ## Risks
          EOF
          echo "Created: $FILE"

  # Cleanup
  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf dist/
      - rm -f {{.BINARY_NAME}}
      - rm -f coverage.out coverage.html
      - task: plugin:clean

  plugin:clean:
    desc: Clean plugin build artifacts
    cmds:
      - rm -f plugins/echo-python/echo.wasm
      - rm -f internal/wasm/testdata/echo.wasm
      - task: test:fixtures:clean

  test:fixtures:clean:
    desc: Clean test fixture build artifacts
    cmds:
      - rm -f test/fixtures/plugins/malformed-json/malformed.wasm
      - rm -f test/fixtures/plugins/empty-stream/empty-stream.wasm
      - rm -f internal/wasm/testdata/malformed.wasm
      - rm -f internal/wasm/testdata/empty-stream.wasm

  # Install tools (prefer brew, use uvx for Python)
  tools:
    desc: Install development tools
    cmds:
      - brew install golangci-lint gofumpt lefthook actionlint goreleaser \
        dprint cocogitto markdownlint-cli \
        binaryen
      - brew install steveyegge/beads/bd
      - curl -Ls https://raw.githubusercontent.com/extism/python-pdk/main/install.sh | bash
      - 'echo "Tools installed. Run lefthook install to set up git hooks."'
      - 'echo "Note: Use uvx yamllint to run yamllint (no install needed)"'

  # Git hooks
  hooks:install:
    desc: Install git hooks
    cmds:
      - lefthook install
      - bd hooks install --chain

  hooks:uninstall:
    desc: Uninstall git hooks
    cmds:
      - bd hooks uninstall
      - lefthook uninstall

  # Release
  release:check:
    desc: Validate goreleaser config
    cmds:
      - goreleaser check

  release:snapshot:
    desc: Build snapshot locally (no publish, local arch only)
    cmds:
      - goreleaser build --snapshot --clean --single-target
