// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 HoloMUSH Contributors

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: holomush/web/v1/web.proto

package webv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/holomush/holomush/pkg/proto/holomush/web/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// WebServiceName is the fully-qualified name of the WebService service.
	WebServiceName = "holomush.web.v1.WebService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// WebServiceLoginProcedure is the fully-qualified name of the WebService's Login RPC.
	WebServiceLoginProcedure = "/holomush.web.v1.WebService/Login"
	// WebServiceSendCommandProcedure is the fully-qualified name of the WebService's SendCommand RPC.
	WebServiceSendCommandProcedure = "/holomush.web.v1.WebService/SendCommand"
	// WebServiceStreamEventsProcedure is the fully-qualified name of the WebService's StreamEvents RPC.
	WebServiceStreamEventsProcedure = "/holomush.web.v1.WebService/StreamEvents"
	// WebServiceDisconnectProcedure is the fully-qualified name of the WebService's Disconnect RPC.
	WebServiceDisconnectProcedure = "/holomush.web.v1.WebService/Disconnect"
)

// WebServiceClient is a client for the holomush.web.v1.WebService service.
type WebServiceClient interface {
	// Authenticate as guest or registered user.
	Login(context.Context, *connect.Request[v1.LoginRequest]) (*connect.Response[v1.LoginResponse], error)
	// Send a game command (say, pose, quit, etc.)
	SendCommand(context.Context, *connect.Request[v1.SendCommandRequest]) (*connect.Response[v1.SendCommandResponse], error)
	// Server-streaming event feed. Client receives game events
	// (say, pose, arrive, leave) as they occur.
	StreamEvents(context.Context, *connect.Request[v1.StreamEventsRequest]) (*connect.ServerStreamForClient[v1.GameEvent], error)
	// Disconnect ends the session and triggers cleanup.
	Disconnect(context.Context, *connect.Request[v1.DisconnectRequest]) (*connect.Response[v1.DisconnectResponse], error)
}

// NewWebServiceClient constructs a client for the holomush.web.v1.WebService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewWebServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) WebServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	webServiceMethods := v1.File_holomush_web_v1_web_proto.Services().ByName("WebService").Methods()
	return &webServiceClient{
		login: connect.NewClient[v1.LoginRequest, v1.LoginResponse](
			httpClient,
			baseURL+WebServiceLoginProcedure,
			connect.WithSchema(webServiceMethods.ByName("Login")),
			connect.WithClientOptions(opts...),
		),
		sendCommand: connect.NewClient[v1.SendCommandRequest, v1.SendCommandResponse](
			httpClient,
			baseURL+WebServiceSendCommandProcedure,
			connect.WithSchema(webServiceMethods.ByName("SendCommand")),
			connect.WithClientOptions(opts...),
		),
		streamEvents: connect.NewClient[v1.StreamEventsRequest, v1.GameEvent](
			httpClient,
			baseURL+WebServiceStreamEventsProcedure,
			connect.WithSchema(webServiceMethods.ByName("StreamEvents")),
			connect.WithClientOptions(opts...),
		),
		disconnect: connect.NewClient[v1.DisconnectRequest, v1.DisconnectResponse](
			httpClient,
			baseURL+WebServiceDisconnectProcedure,
			connect.WithSchema(webServiceMethods.ByName("Disconnect")),
			connect.WithClientOptions(opts...),
		),
	}
}

// webServiceClient implements WebServiceClient.
type webServiceClient struct {
	login        *connect.Client[v1.LoginRequest, v1.LoginResponse]
	sendCommand  *connect.Client[v1.SendCommandRequest, v1.SendCommandResponse]
	streamEvents *connect.Client[v1.StreamEventsRequest, v1.GameEvent]
	disconnect   *connect.Client[v1.DisconnectRequest, v1.DisconnectResponse]
}

// Login calls holomush.web.v1.WebService.Login.
func (c *webServiceClient) Login(ctx context.Context, req *connect.Request[v1.LoginRequest]) (*connect.Response[v1.LoginResponse], error) {
	return c.login.CallUnary(ctx, req)
}

// SendCommand calls holomush.web.v1.WebService.SendCommand.
func (c *webServiceClient) SendCommand(ctx context.Context, req *connect.Request[v1.SendCommandRequest]) (*connect.Response[v1.SendCommandResponse], error) {
	return c.sendCommand.CallUnary(ctx, req)
}

// StreamEvents calls holomush.web.v1.WebService.StreamEvents.
func (c *webServiceClient) StreamEvents(ctx context.Context, req *connect.Request[v1.StreamEventsRequest]) (*connect.ServerStreamForClient[v1.GameEvent], error) {
	return c.streamEvents.CallServerStream(ctx, req)
}

// Disconnect calls holomush.web.v1.WebService.Disconnect.
func (c *webServiceClient) Disconnect(ctx context.Context, req *connect.Request[v1.DisconnectRequest]) (*connect.Response[v1.DisconnectResponse], error) {
	return c.disconnect.CallUnary(ctx, req)
}

// WebServiceHandler is an implementation of the holomush.web.v1.WebService service.
type WebServiceHandler interface {
	// Authenticate as guest or registered user.
	Login(context.Context, *connect.Request[v1.LoginRequest]) (*connect.Response[v1.LoginResponse], error)
	// Send a game command (say, pose, quit, etc.)
	SendCommand(context.Context, *connect.Request[v1.SendCommandRequest]) (*connect.Response[v1.SendCommandResponse], error)
	// Server-streaming event feed. Client receives game events
	// (say, pose, arrive, leave) as they occur.
	StreamEvents(context.Context, *connect.Request[v1.StreamEventsRequest], *connect.ServerStream[v1.GameEvent]) error
	// Disconnect ends the session and triggers cleanup.
	Disconnect(context.Context, *connect.Request[v1.DisconnectRequest]) (*connect.Response[v1.DisconnectResponse], error)
}

// NewWebServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewWebServiceHandler(svc WebServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	webServiceMethods := v1.File_holomush_web_v1_web_proto.Services().ByName("WebService").Methods()
	webServiceLoginHandler := connect.NewUnaryHandler(
		WebServiceLoginProcedure,
		svc.Login,
		connect.WithSchema(webServiceMethods.ByName("Login")),
		connect.WithHandlerOptions(opts...),
	)
	webServiceSendCommandHandler := connect.NewUnaryHandler(
		WebServiceSendCommandProcedure,
		svc.SendCommand,
		connect.WithSchema(webServiceMethods.ByName("SendCommand")),
		connect.WithHandlerOptions(opts...),
	)
	webServiceStreamEventsHandler := connect.NewServerStreamHandler(
		WebServiceStreamEventsProcedure,
		svc.StreamEvents,
		connect.WithSchema(webServiceMethods.ByName("StreamEvents")),
		connect.WithHandlerOptions(opts...),
	)
	webServiceDisconnectHandler := connect.NewUnaryHandler(
		WebServiceDisconnectProcedure,
		svc.Disconnect,
		connect.WithSchema(webServiceMethods.ByName("Disconnect")),
		connect.WithHandlerOptions(opts...),
	)
	return "/holomush.web.v1.WebService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case WebServiceLoginProcedure:
			webServiceLoginHandler.ServeHTTP(w, r)
		case WebServiceSendCommandProcedure:
			webServiceSendCommandHandler.ServeHTTP(w, r)
		case WebServiceStreamEventsProcedure:
			webServiceStreamEventsHandler.ServeHTTP(w, r)
		case WebServiceDisconnectProcedure:
			webServiceDisconnectHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedWebServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedWebServiceHandler struct{}

func (UnimplementedWebServiceHandler) Login(context.Context, *connect.Request[v1.LoginRequest]) (*connect.Response[v1.LoginResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("holomush.web.v1.WebService.Login is not implemented"))
}

func (UnimplementedWebServiceHandler) SendCommand(context.Context, *connect.Request[v1.SendCommandRequest]) (*connect.Response[v1.SendCommandResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("holomush.web.v1.WebService.SendCommand is not implemented"))
}

func (UnimplementedWebServiceHandler) StreamEvents(context.Context, *connect.Request[v1.StreamEventsRequest], *connect.ServerStream[v1.GameEvent]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("holomush.web.v1.WebService.StreamEvents is not implemented"))
}

func (UnimplementedWebServiceHandler) Disconnect(context.Context, *connect.Request[v1.DisconnectRequest]) (*connect.Response[v1.DisconnectResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("holomush.web.v1.WebService.Disconnect is not implemented"))
}
