// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 HoloMUSH Contributors

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: holomush/core/v1/core.proto

package corev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ControlSignal int32

const (
	ControlSignal_CONTROL_SIGNAL_UNSPECIFIED     ControlSignal = 0
	ControlSignal_CONTROL_SIGNAL_REPLAY_COMPLETE ControlSignal = 1
	ControlSignal_CONTROL_SIGNAL_STREAM_CLOSED   ControlSignal = 2
)

// Enum value maps for ControlSignal.
var (
	ControlSignal_name = map[int32]string{
		0: "CONTROL_SIGNAL_UNSPECIFIED",
		1: "CONTROL_SIGNAL_REPLAY_COMPLETE",
		2: "CONTROL_SIGNAL_STREAM_CLOSED",
	}
	ControlSignal_value = map[string]int32{
		"CONTROL_SIGNAL_UNSPECIFIED":     0,
		"CONTROL_SIGNAL_REPLAY_COMPLETE": 1,
		"CONTROL_SIGNAL_STREAM_CLOSED":   2,
	}
)

func (x ControlSignal) Enum() *ControlSignal {
	p := new(ControlSignal)
	*p = x
	return p
}

func (x ControlSignal) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ControlSignal) Descriptor() protoreflect.EnumDescriptor {
	return file_holomush_core_v1_core_proto_enumTypes[0].Descriptor()
}

func (ControlSignal) Type() protoreflect.EnumType {
	return &file_holomush_core_v1_core_proto_enumTypes[0]
}

func (x ControlSignal) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ControlSignal.Descriptor instead.
func (ControlSignal) EnumDescriptor() ([]byte, []int) {
	return file_holomush_core_v1_core_proto_rawDescGZIP(), []int{0}
}

// RequestMeta contains metadata for request correlation and debugging.
type RequestMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"` // ULID for log correlation
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestMeta) Reset() {
	*x = RequestMeta{}
	mi := &file_holomush_core_v1_core_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestMeta) ProtoMessage() {}

func (x *RequestMeta) ProtoReflect() protoreflect.Message {
	mi := &file_holomush_core_v1_core_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestMeta.ProtoReflect.Descriptor instead.
func (*RequestMeta) Descriptor() ([]byte, []int) {
	return file_holomush_core_v1_core_proto_rawDescGZIP(), []int{0}
}

func (x *RequestMeta) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *RequestMeta) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// ResponseMeta contains metadata echoed back from requests.
type ResponseMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"` // Echoed from request
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseMeta) Reset() {
	*x = ResponseMeta{}
	mi := &file_holomush_core_v1_core_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseMeta) ProtoMessage() {}

func (x *ResponseMeta) ProtoReflect() protoreflect.Message {
	mi := &file_holomush_core_v1_core_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseMeta.ProtoReflect.Descriptor instead.
func (*ResponseMeta) Descriptor() ([]byte, []int) {
	return file_holomush_core_v1_core_proto_rawDescGZIP(), []int{1}
}

func (x *ResponseMeta) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ResponseMeta) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type AuthenticateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *RequestMeta           `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	ClientType    string                 `protobuf:"bytes,4,opt,name=client_type,json=clientType,proto3" json:"client_type,omitempty"` // "terminal", "comms_hub", "telnet"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthenticateRequest) Reset() {
	*x = AuthenticateRequest{}
	mi := &file_holomush_core_v1_core_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticateRequest) ProtoMessage() {}

func (x *AuthenticateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_holomush_core_v1_core_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticateRequest.ProtoReflect.Descriptor instead.
func (*AuthenticateRequest) Descriptor() ([]byte, []int) {
	return file_holomush_core_v1_core_proto_rawDescGZIP(), []int{2}
}

func (x *AuthenticateRequest) GetMeta() *RequestMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *AuthenticateRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AuthenticateRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *AuthenticateRequest) GetClientType() string {
	if x != nil {
		return x.ClientType
	}
	return ""
}

type AuthenticateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *ResponseMeta          `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	SessionId     string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	CharacterId   string                 `protobuf:"bytes,4,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
	CharacterName string                 `protobuf:"bytes,5,opt,name=character_name,json=characterName,proto3" json:"character_name,omitempty"`
	Error         string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	ConnectionId  string                 `protobuf:"bytes,7,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthenticateResponse) Reset() {
	*x = AuthenticateResponse{}
	mi := &file_holomush_core_v1_core_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticateResponse) ProtoMessage() {}

func (x *AuthenticateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_holomush_core_v1_core_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticateResponse.ProtoReflect.Descriptor instead.
func (*AuthenticateResponse) Descriptor() ([]byte, []int) {
	return file_holomush_core_v1_core_proto_rawDescGZIP(), []int{3}
}

func (x *AuthenticateResponse) GetMeta() *ResponseMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *AuthenticateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AuthenticateResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AuthenticateResponse) GetCharacterId() string {
	if x != nil {
		return x.CharacterId
	}
	return ""
}

func (x *AuthenticateResponse) GetCharacterName() string {
	if x != nil {
		return x.CharacterName
	}
	return ""
}

func (x *AuthenticateResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *AuthenticateResponse) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

type HandleCommandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *RequestMeta           `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Command       string                 `protobuf:"bytes,3,opt,name=command,proto3" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandleCommandRequest) Reset() {
	*x = HandleCommandRequest{}
	mi := &file_holomush_core_v1_core_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandleCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleCommandRequest) ProtoMessage() {}

func (x *HandleCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_holomush_core_v1_core_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleCommandRequest.ProtoReflect.Descriptor instead.
func (*HandleCommandRequest) Descriptor() ([]byte, []int) {
	return file_holomush_core_v1_core_proto_rawDescGZIP(), []int{4}
}

func (x *HandleCommandRequest) GetMeta() *RequestMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *HandleCommandRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *HandleCommandRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

type HandleCommandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *ResponseMeta          `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandleCommandResponse) Reset() {
	*x = HandleCommandResponse{}
	mi := &file_holomush_core_v1_core_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandleCommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleCommandResponse) ProtoMessage() {}

func (x *HandleCommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_holomush_core_v1_core_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleCommandResponse.ProtoReflect.Descriptor instead.
func (*HandleCommandResponse) Descriptor() ([]byte, []int) {
	return file_holomush_core_v1_core_proto_rawDescGZIP(), []int{5}
}

func (x *HandleCommandResponse) GetMeta() *ResponseMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *HandleCommandResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *HandleCommandResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type SubscribeRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Meta             *RequestMeta           `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	SessionId        string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Streams          []string               `protobuf:"bytes,3,rep,name=streams,proto3" json:"streams,omitempty"`
	ReplayFromCursor bool                   `protobuf:"varint,4,opt,name=replay_from_cursor,json=replayFromCursor,proto3" json:"replay_from_cursor,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_holomush_core_v1_core_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_holomush_core_v1_core_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_holomush_core_v1_core_proto_rawDescGZIP(), []int{6}
}

func (x *SubscribeRequest) GetMeta() *RequestMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *SubscribeRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SubscribeRequest) GetStreams() []string {
	if x != nil {
		return x.Streams
	}
	return nil
}

func (x *SubscribeRequest) GetReplayFromCursor() bool {
	if x != nil {
		return x.ReplayFromCursor
	}
	return false
}

type EventFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Stream        string                 `protobuf:"bytes,2,opt,name=stream,proto3" json:"stream,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ActorType     string                 `protobuf:"bytes,5,opt,name=actor_type,json=actorType,proto3" json:"actor_type,omitempty"`
	ActorId       string                 `protobuf:"bytes,6,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	Payload       []byte                 `protobuf:"bytes,7,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventFrame) Reset() {
	*x = EventFrame{}
	mi := &file_holomush_core_v1_core_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventFrame) ProtoMessage() {}

func (x *EventFrame) ProtoReflect() protoreflect.Message {
	mi := &file_holomush_core_v1_core_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventFrame.ProtoReflect.Descriptor instead.
func (*EventFrame) Descriptor() ([]byte, []int) {
	return file_holomush_core_v1_core_proto_rawDescGZIP(), []int{7}
}

func (x *EventFrame) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EventFrame) GetStream() string {
	if x != nil {
		return x.Stream
	}
	return ""
}

func (x *EventFrame) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *EventFrame) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *EventFrame) GetActorType() string {
	if x != nil {
		return x.ActorType
	}
	return ""
}

func (x *EventFrame) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *EventFrame) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type ControlFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Signal        ControlSignal          `protobuf:"varint,1,opt,name=signal,proto3,enum=holomush.core.v1.ControlSignal" json:"signal,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlFrame) Reset() {
	*x = ControlFrame{}
	mi := &file_holomush_core_v1_core_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlFrame) ProtoMessage() {}

func (x *ControlFrame) ProtoReflect() protoreflect.Message {
	mi := &file_holomush_core_v1_core_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlFrame.ProtoReflect.Descriptor instead.
func (*ControlFrame) Descriptor() ([]byte, []int) {
	return file_holomush_core_v1_core_proto_rawDescGZIP(), []int{8}
}

func (x *ControlFrame) GetSignal() ControlSignal {
	if x != nil {
		return x.Signal
	}
	return ControlSignal_CONTROL_SIGNAL_UNSPECIFIED
}

func (x *ControlFrame) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SubscribeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Frame:
	//
	//	*SubscribeResponse_Event
	//	*SubscribeResponse_Control
	Frame         isSubscribeResponse_Frame `protobuf_oneof:"frame"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeResponse) Reset() {
	*x = SubscribeResponse{}
	mi := &file_holomush_core_v1_core_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeResponse) ProtoMessage() {}

func (x *SubscribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_holomush_core_v1_core_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeResponse.ProtoReflect.Descriptor instead.
func (*SubscribeResponse) Descriptor() ([]byte, []int) {
	return file_holomush_core_v1_core_proto_rawDescGZIP(), []int{9}
}

func (x *SubscribeResponse) GetFrame() isSubscribeResponse_Frame {
	if x != nil {
		return x.Frame
	}
	return nil
}

func (x *SubscribeResponse) GetEvent() *EventFrame {
	if x != nil {
		if x, ok := x.Frame.(*SubscribeResponse_Event); ok {
			return x.Event
		}
	}
	return nil
}

func (x *SubscribeResponse) GetControl() *ControlFrame {
	if x != nil {
		if x, ok := x.Frame.(*SubscribeResponse_Control); ok {
			return x.Control
		}
	}
	return nil
}

type isSubscribeResponse_Frame interface {
	isSubscribeResponse_Frame()
}

type SubscribeResponse_Event struct {
	Event *EventFrame `protobuf:"bytes,1,opt,name=event,proto3,oneof"`
}

type SubscribeResponse_Control struct {
	Control *ControlFrame `protobuf:"bytes,2,opt,name=control,proto3,oneof"`
}

func (*SubscribeResponse_Event) isSubscribeResponse_Frame() {}

func (*SubscribeResponse_Control) isSubscribeResponse_Frame() {}

type DisconnectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *RequestMeta           `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ConnectionId  string                 `protobuf:"bytes,3,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"` // optional: remove specific connection
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisconnectRequest) Reset() {
	*x = DisconnectRequest{}
	mi := &file_holomush_core_v1_core_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisconnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisconnectRequest) ProtoMessage() {}

func (x *DisconnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_holomush_core_v1_core_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisconnectRequest.ProtoReflect.Descriptor instead.
func (*DisconnectRequest) Descriptor() ([]byte, []int) {
	return file_holomush_core_v1_core_proto_rawDescGZIP(), []int{10}
}

func (x *DisconnectRequest) GetMeta() *RequestMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *DisconnectRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *DisconnectRequest) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

type DisconnectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *ResponseMeta          `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisconnectResponse) Reset() {
	*x = DisconnectResponse{}
	mi := &file_holomush_core_v1_core_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisconnectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisconnectResponse) ProtoMessage() {}

func (x *DisconnectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_holomush_core_v1_core_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisconnectResponse.ProtoReflect.Descriptor instead.
func (*DisconnectResponse) Descriptor() ([]byte, []int) {
	return file_holomush_core_v1_core_proto_rawDescGZIP(), []int{11}
}

func (x *DisconnectResponse) GetMeta() *ResponseMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *DisconnectResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_holomush_core_v1_core_proto protoreflect.FileDescriptor

const file_holomush_core_v1_core_proto_rawDesc = "" +
	"\n" +
	"\x1bholomush/core/v1/core.proto\x12\x10holomush.core.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"f\n" +
	"\vRequestMeta\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"g\n" +
	"\fResponseMeta\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\xa1\x01\n" +
	"\x13AuthenticateRequest\x121\n" +
	"\x04meta\x18\x01 \x01(\v2\x1d.holomush.core.v1.RequestMetaR\x04meta\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12\x1f\n" +
	"\vclient_type\x18\x04 \x01(\tR\n" +
	"clientType\"\x88\x02\n" +
	"\x14AuthenticateResponse\x122\n" +
	"\x04meta\x18\x01 \x01(\v2\x1e.holomush.core.v1.ResponseMetaR\x04meta\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12!\n" +
	"\fcharacter_id\x18\x04 \x01(\tR\vcharacterId\x12%\n" +
	"\x0echaracter_name\x18\x05 \x01(\tR\rcharacterName\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\x12#\n" +
	"\rconnection_id\x18\a \x01(\tR\fconnectionId\"\x82\x01\n" +
	"\x14HandleCommandRequest\x121\n" +
	"\x04meta\x18\x01 \x01(\v2\x1d.holomush.core.v1.RequestMetaR\x04meta\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x18\n" +
	"\acommand\x18\x03 \x01(\tR\acommand\"\x81\x01\n" +
	"\x15HandleCommandResponse\x122\n" +
	"\x04meta\x18\x01 \x01(\v2\x1e.holomush.core.v1.ResponseMetaR\x04meta\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05errorJ\x04\b\x03\x10\x04\"\xac\x01\n" +
	"\x10SubscribeRequest\x121\n" +
	"\x04meta\x18\x01 \x01(\v2\x1d.holomush.core.v1.RequestMetaR\x04meta\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x18\n" +
	"\astreams\x18\x03 \x03(\tR\astreams\x12,\n" +
	"\x12replay_from_cursor\x18\x04 \x01(\bR\x10replayFromCursor\"\xd6\x01\n" +
	"\n" +
	"EventFrame\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06stream\x18\x02 \x01(\tR\x06stream\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x1d\n" +
	"\n" +
	"actor_type\x18\x05 \x01(\tR\tactorType\x12\x19\n" +
	"\bactor_id\x18\x06 \x01(\tR\aactorId\x12\x18\n" +
	"\apayload\x18\a \x01(\fR\apayload\"a\n" +
	"\fControlFrame\x127\n" +
	"\x06signal\x18\x01 \x01(\x0e2\x1f.holomush.core.v1.ControlSignalR\x06signal\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x8e\x01\n" +
	"\x11SubscribeResponse\x124\n" +
	"\x05event\x18\x01 \x01(\v2\x1c.holomush.core.v1.EventFrameH\x00R\x05event\x12:\n" +
	"\acontrol\x18\x02 \x01(\v2\x1e.holomush.core.v1.ControlFrameH\x00R\acontrolB\a\n" +
	"\x05frame\"\x8a\x01\n" +
	"\x11DisconnectRequest\x121\n" +
	"\x04meta\x18\x01 \x01(\v2\x1d.holomush.core.v1.RequestMetaR\x04meta\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12#\n" +
	"\rconnection_id\x18\x03 \x01(\tR\fconnectionId\"b\n" +
	"\x12DisconnectResponse\x122\n" +
	"\x04meta\x18\x01 \x01(\v2\x1e.holomush.core.v1.ResponseMetaR\x04meta\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess*u\n" +
	"\rControlSignal\x12\x1e\n" +
	"\x1aCONTROL_SIGNAL_UNSPECIFIED\x10\x00\x12\"\n" +
	"\x1eCONTROL_SIGNAL_REPLAY_COMPLETE\x10\x01\x12 \n" +
	"\x1cCONTROL_SIGNAL_STREAM_CLOSED\x10\x022\xff\x02\n" +
	"\vCoreService\x12]\n" +
	"\fAuthenticate\x12%.holomush.core.v1.AuthenticateRequest\x1a&.holomush.core.v1.AuthenticateResponse\x12`\n" +
	"\rHandleCommand\x12&.holomush.core.v1.HandleCommandRequest\x1a'.holomush.core.v1.HandleCommandResponse\x12V\n" +
	"\tSubscribe\x12\".holomush.core.v1.SubscribeRequest\x1a#.holomush.core.v1.SubscribeResponse0\x01\x12W\n" +
	"\n" +
	"Disconnect\x12#.holomush.core.v1.DisconnectRequest\x1a$.holomush.core.v1.DisconnectResponseB\xc3\x01\n" +
	"\x14com.holomush.core.v1B\tCoreProtoP\x01Z>github.com/holomush/holomush/pkg/proto/holomush/core/v1;corev1\xa2\x02\x03HCX\xaa\x02\x10Holomush.Core.V1\xca\x02\x10Holomush\\Core\\V1\xe2\x02\x1cHolomush\\Core\\V1\\GPBMetadata\xea\x02\x12Holomush::Core::V1b\x06proto3"

var (
	file_holomush_core_v1_core_proto_rawDescOnce sync.Once
	file_holomush_core_v1_core_proto_rawDescData []byte
)

func file_holomush_core_v1_core_proto_rawDescGZIP() []byte {
	file_holomush_core_v1_core_proto_rawDescOnce.Do(func() {
		file_holomush_core_v1_core_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_holomush_core_v1_core_proto_rawDesc), len(file_holomush_core_v1_core_proto_rawDesc)))
	})
	return file_holomush_core_v1_core_proto_rawDescData
}

var file_holomush_core_v1_core_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_holomush_core_v1_core_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_holomush_core_v1_core_proto_goTypes = []any{
	(ControlSignal)(0),            // 0: holomush.core.v1.ControlSignal
	(*RequestMeta)(nil),           // 1: holomush.core.v1.RequestMeta
	(*ResponseMeta)(nil),          // 2: holomush.core.v1.ResponseMeta
	(*AuthenticateRequest)(nil),   // 3: holomush.core.v1.AuthenticateRequest
	(*AuthenticateResponse)(nil),  // 4: holomush.core.v1.AuthenticateResponse
	(*HandleCommandRequest)(nil),  // 5: holomush.core.v1.HandleCommandRequest
	(*HandleCommandResponse)(nil), // 6: holomush.core.v1.HandleCommandResponse
	(*SubscribeRequest)(nil),      // 7: holomush.core.v1.SubscribeRequest
	(*EventFrame)(nil),            // 8: holomush.core.v1.EventFrame
	(*ControlFrame)(nil),          // 9: holomush.core.v1.ControlFrame
	(*SubscribeResponse)(nil),     // 10: holomush.core.v1.SubscribeResponse
	(*DisconnectRequest)(nil),     // 11: holomush.core.v1.DisconnectRequest
	(*DisconnectResponse)(nil),    // 12: holomush.core.v1.DisconnectResponse
	(*timestamppb.Timestamp)(nil), // 13: google.protobuf.Timestamp
}
var file_holomush_core_v1_core_proto_depIdxs = []int32{
	13, // 0: holomush.core.v1.RequestMeta.timestamp:type_name -> google.protobuf.Timestamp
	13, // 1: holomush.core.v1.ResponseMeta.timestamp:type_name -> google.protobuf.Timestamp
	1,  // 2: holomush.core.v1.AuthenticateRequest.meta:type_name -> holomush.core.v1.RequestMeta
	2,  // 3: holomush.core.v1.AuthenticateResponse.meta:type_name -> holomush.core.v1.ResponseMeta
	1,  // 4: holomush.core.v1.HandleCommandRequest.meta:type_name -> holomush.core.v1.RequestMeta
	2,  // 5: holomush.core.v1.HandleCommandResponse.meta:type_name -> holomush.core.v1.ResponseMeta
	1,  // 6: holomush.core.v1.SubscribeRequest.meta:type_name -> holomush.core.v1.RequestMeta
	13, // 7: holomush.core.v1.EventFrame.timestamp:type_name -> google.protobuf.Timestamp
	0,  // 8: holomush.core.v1.ControlFrame.signal:type_name -> holomush.core.v1.ControlSignal
	8,  // 9: holomush.core.v1.SubscribeResponse.event:type_name -> holomush.core.v1.EventFrame
	9,  // 10: holomush.core.v1.SubscribeResponse.control:type_name -> holomush.core.v1.ControlFrame
	1,  // 11: holomush.core.v1.DisconnectRequest.meta:type_name -> holomush.core.v1.RequestMeta
	2,  // 12: holomush.core.v1.DisconnectResponse.meta:type_name -> holomush.core.v1.ResponseMeta
	3,  // 13: holomush.core.v1.CoreService.Authenticate:input_type -> holomush.core.v1.AuthenticateRequest
	5,  // 14: holomush.core.v1.CoreService.HandleCommand:input_type -> holomush.core.v1.HandleCommandRequest
	7,  // 15: holomush.core.v1.CoreService.Subscribe:input_type -> holomush.core.v1.SubscribeRequest
	11, // 16: holomush.core.v1.CoreService.Disconnect:input_type -> holomush.core.v1.DisconnectRequest
	4,  // 17: holomush.core.v1.CoreService.Authenticate:output_type -> holomush.core.v1.AuthenticateResponse
	6,  // 18: holomush.core.v1.CoreService.HandleCommand:output_type -> holomush.core.v1.HandleCommandResponse
	10, // 19: holomush.core.v1.CoreService.Subscribe:output_type -> holomush.core.v1.SubscribeResponse
	12, // 20: holomush.core.v1.CoreService.Disconnect:output_type -> holomush.core.v1.DisconnectResponse
	17, // [17:21] is the sub-list for method output_type
	13, // [13:17] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_holomush_core_v1_core_proto_init() }
func file_holomush_core_v1_core_proto_init() {
	if File_holomush_core_v1_core_proto != nil {
		return
	}
	file_holomush_core_v1_core_proto_msgTypes[9].OneofWrappers = []any{
		(*SubscribeResponse_Event)(nil),
		(*SubscribeResponse_Control)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_holomush_core_v1_core_proto_rawDesc), len(file_holomush_core_v1_core_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_holomush_core_v1_core_proto_goTypes,
		DependencyIndexes: file_holomush_core_v1_core_proto_depIdxs,
		EnumInfos:         file_holomush_core_v1_core_proto_enumTypes,
		MessageInfos:      file_holomush_core_v1_core_proto_msgTypes,
	}.Build()
	File_holomush_core_v1_core_proto = out.File
	file_holomush_core_v1_core_proto_goTypes = nil
	file_holomush_core_v1_core_proto_depIdxs = nil
}
