// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 HoloMUSH Contributors

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: holomush/plugin/host/v1/settings.proto

package hostv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SettingsService_GetSetting_FullMethodName = "/holomush.plugin.host.v1.SettingsService/GetSetting"
	SettingsService_SetSetting_FullMethodName = "/holomush.plugin.host.v1.SettingsService/SetSetting"
)

// SettingsServiceClient is the client API for SettingsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SettingsService is the host-brokered `settings` capability: a plugin reads
// and writes owner-partitioned settings in the GAME/PLAYER/CHARACTER scopes.
// Carved from the former PluginHostService (holomush-eykuh.1). Served by
// settingsServer in internal/plugin/goplugin/host_capability_servers.go.
type SettingsServiceClient interface {
	// GetSetting reads a single-scope setting in the calling plugin's owner
	// partition (owner bound host-side from the authenticated plugin name, never
	// from the request). The handler resolves SettingScope to its backing store;
	// a missing key returns a successful response with found=false, never a
	// codes.NotFound status error.
	GetSetting(ctx context.Context, in *GetSettingRequest, opts ...grpc.CallOption) (*GetSettingResponse, error)
	// SetSetting writes a single-scope setting in the calling plugin's partition;
	// GAME scope requires an operator authorization decision (host-enforced, not
	// trusted from the wire). The owner partition is bound host-side from the
	// authenticated plugin name.
	SetSetting(ctx context.Context, in *SetSettingRequest, opts ...grpc.CallOption) (*SetSettingResponse, error)
}

type settingsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSettingsServiceClient(cc grpc.ClientConnInterface) SettingsServiceClient {
	return &settingsServiceClient{cc}
}

func (c *settingsServiceClient) GetSetting(ctx context.Context, in *GetSettingRequest, opts ...grpc.CallOption) (*GetSettingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSettingResponse)
	err := c.cc.Invoke(ctx, SettingsService_GetSetting_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *settingsServiceClient) SetSetting(ctx context.Context, in *SetSettingRequest, opts ...grpc.CallOption) (*SetSettingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetSettingResponse)
	err := c.cc.Invoke(ctx, SettingsService_SetSetting_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SettingsServiceServer is the server API for SettingsService service.
// All implementations must embed UnimplementedSettingsServiceServer
// for forward compatibility.
//
// SettingsService is the host-brokered `settings` capability: a plugin reads
// and writes owner-partitioned settings in the GAME/PLAYER/CHARACTER scopes.
// Carved from the former PluginHostService (holomush-eykuh.1). Served by
// settingsServer in internal/plugin/goplugin/host_capability_servers.go.
type SettingsServiceServer interface {
	// GetSetting reads a single-scope setting in the calling plugin's owner
	// partition (owner bound host-side from the authenticated plugin name, never
	// from the request). The handler resolves SettingScope to its backing store;
	// a missing key returns a successful response with found=false, never a
	// codes.NotFound status error.
	GetSetting(context.Context, *GetSettingRequest) (*GetSettingResponse, error)
	// SetSetting writes a single-scope setting in the calling plugin's partition;
	// GAME scope requires an operator authorization decision (host-enforced, not
	// trusted from the wire). The owner partition is bound host-side from the
	// authenticated plugin name.
	SetSetting(context.Context, *SetSettingRequest) (*SetSettingResponse, error)
	mustEmbedUnimplementedSettingsServiceServer()
}

// UnimplementedSettingsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSettingsServiceServer struct{}

func (UnimplementedSettingsServiceServer) GetSetting(context.Context, *GetSettingRequest) (*GetSettingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSetting not implemented")
}
func (UnimplementedSettingsServiceServer) SetSetting(context.Context, *SetSettingRequest) (*SetSettingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetSetting not implemented")
}
func (UnimplementedSettingsServiceServer) mustEmbedUnimplementedSettingsServiceServer() {}
func (UnimplementedSettingsServiceServer) testEmbeddedByValue()                         {}

// UnsafeSettingsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SettingsServiceServer will
// result in compilation errors.
type UnsafeSettingsServiceServer interface {
	mustEmbedUnimplementedSettingsServiceServer()
}

func RegisterSettingsServiceServer(s grpc.ServiceRegistrar, srv SettingsServiceServer) {
	// If the following call panics, it indicates UnimplementedSettingsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SettingsService_ServiceDesc, srv)
}

func _SettingsService_GetSetting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSettingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SettingsServiceServer).GetSetting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SettingsService_GetSetting_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SettingsServiceServer).GetSetting(ctx, req.(*GetSettingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SettingsService_SetSetting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetSettingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SettingsServiceServer).SetSetting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SettingsService_SetSetting_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SettingsServiceServer).SetSetting(ctx, req.(*SetSettingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SettingsService_ServiceDesc is the grpc.ServiceDesc for SettingsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SettingsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "holomush.plugin.host.v1.SettingsService",
	HandlerType: (*SettingsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSetting",
			Handler:    _SettingsService_GetSetting_Handler,
		},
		{
			MethodName: "SetSetting",
			Handler:    _SettingsService_SetSetting_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "holomush/plugin/host/v1/settings.proto",
}
