// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 HoloMUSH Contributors

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: holomush/plugin/host/v1/stream.proto

package hostv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// StreamReplayMode controls how a stream subscription's initial replay
// behaves when added via AddSessionStream.
type StreamReplayMode int32

const (
	// Zero value; treated as FROM_CURSOR for backward compatibility.
	StreamReplayMode_STREAM_REPLAY_MODE_UNSPECIFIED StreamReplayMode = 0
	// Replay from the session's saved cursor for the stream (catch-up).
	StreamReplayMode_STREAM_REPLAY_MODE_FROM_CURSOR StreamReplayMode = 1
	// Skip historical replay and deliver only newly-arriving events.
	StreamReplayMode_STREAM_REPLAY_MODE_LIVE_ONLY StreamReplayMode = 2
)

// Enum value maps for StreamReplayMode.
var (
	StreamReplayMode_name = map[int32]string{
		0: "STREAM_REPLAY_MODE_UNSPECIFIED",
		1: "STREAM_REPLAY_MODE_FROM_CURSOR",
		2: "STREAM_REPLAY_MODE_LIVE_ONLY",
	}
	StreamReplayMode_value = map[string]int32{
		"STREAM_REPLAY_MODE_UNSPECIFIED": 0,
		"STREAM_REPLAY_MODE_FROM_CURSOR": 1,
		"STREAM_REPLAY_MODE_LIVE_ONLY":   2,
	}
)

func (x StreamReplayMode) Enum() *StreamReplayMode {
	p := new(StreamReplayMode)
	*p = x
	return p
}

func (x StreamReplayMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StreamReplayMode) Descriptor() protoreflect.EnumDescriptor {
	return file_holomush_plugin_host_v1_stream_proto_enumTypes[0].Descriptor()
}

func (StreamReplayMode) Type() protoreflect.EnumType {
	return &file_holomush_plugin_host_v1_stream_proto_enumTypes[0]
}

func (x StreamReplayMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StreamReplayMode.Descriptor instead.
func (StreamReplayMode) EnumDescriptor() ([]byte, []int) {
	return file_holomush_plugin_host_v1_stream_proto_rawDescGZIP(), []int{0}
}

// Event is the host→plugin delivery shape for one game event (the proto mirror
// of pkg/plugin.Event), returned in a QueryStreamHistory page.
type Event struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ULID string uniquely identifying the event; also its bus dedup key.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Source stream this event belongs to, in legacy "prefix:id" form
	// (e.g. "location:loc_abc123"). Translated to the dot-delimited NATS subject
	// at the emit boundary.
	Stream string `protobuf:"bytes,2,opt,name=stream,proto3" json:"stream,omitempty"`
	// Event-type discriminator (e.g. "say", "pose", "arrive", "leave",
	// "system") that the plugin handler switches on.
	Type string `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	// Event occurrence time in Unix milliseconds (host clock).
	Timestamp int64 `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Actor kind as a string (e.g. "character", "system", "plugin"). Carried as
	// a string rather than an enum for forward-compat; the SDK maps it to its
	// ActorKind type. Distinct from the bus-internal ActorKind enum.
	ActorKind string `protobuf:"bytes,5,opt,name=actor_kind,json=actorKind,proto3" json:"actor_kind,omitempty"`
	// ULID of the actor that caused the event (the character/system/plugin id).
	ActorId string `protobuf:"bytes,6,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	// JSON-encoded event payload (max 64 KiB); the plugin decodes it per the
	// event type's schema.
	Payload string `protobuf:"bytes,7,opt,name=payload,proto3" json:"payload,omitempty"`
	// cursor is the opaque pagination token for this event. Pass as
	// QueryStreamHistoryRequest.cursor on the next call to page backward from
	// this position. Empty on events received via delivery (not history). Treat
	// as an opaque blob.
	Cursor        []byte `protobuf:"bytes,8,opt,name=cursor,proto3" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_holomush_plugin_host_v1_stream_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_holomush_plugin_host_v1_stream_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_holomush_plugin_host_v1_stream_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Event) GetStream() string {
	if x != nil {
		return x.Stream
	}
	return ""
}

func (x *Event) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Event) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Event) GetActorKind() string {
	if x != nil {
		return x.ActorKind
	}
	return ""
}

func (x *Event) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *Event) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *Event) GetCursor() []byte {
	if x != nil {
		return x.Cursor
	}
	return nil
}

// QueryStreamHistoryRequest selects a backward-paginated tail of a stream for
// plugin-side display.
type QueryStreamHistoryRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stream to read history from (legacy "prefix:id" form).
	Stream string `protobuf:"bytes,1,opt,name=stream,proto3" json:"stream,omitempty"`
	// Page size; negative is rejected, values above 500 are clamped to 500.
	Count int32 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	// Epoch milliseconds. Events before this time are excluded. 0 means no lower bound.
	NotBeforeMs int64 `protobuf:"varint,3,opt,name=not_before_ms,json=notBeforeMs,proto3" json:"not_before_ms,omitempty"`
	// cursor is the opaque pagination cursor from a previous response.
	// Events older than the cursor position are returned. Empty = start from latest.
	Cursor        []byte `protobuf:"bytes,4,opt,name=cursor,proto3" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryStreamHistoryRequest) Reset() {
	*x = QueryStreamHistoryRequest{}
	mi := &file_holomush_plugin_host_v1_stream_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryStreamHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryStreamHistoryRequest) ProtoMessage() {}

func (x *QueryStreamHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_holomush_plugin_host_v1_stream_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryStreamHistoryRequest.ProtoReflect.Descriptor instead.
func (*QueryStreamHistoryRequest) Descriptor() ([]byte, []int) {
	return file_holomush_plugin_host_v1_stream_proto_rawDescGZIP(), []int{1}
}

func (x *QueryStreamHistoryRequest) GetStream() string {
	if x != nil {
		return x.Stream
	}
	return ""
}

func (x *QueryStreamHistoryRequest) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *QueryStreamHistoryRequest) GetNotBeforeMs() int64 {
	if x != nil {
		return x.NotBeforeMs
	}
	return 0
}

func (x *QueryStreamHistoryRequest) GetCursor() []byte {
	if x != nil {
		return x.Cursor
	}
	return nil
}

// QueryStreamHistoryResponse returns one history page plus the cursor for the
// next (older) page.
type QueryStreamHistoryResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The page of events in ascending (oldest→newest) order; each carries its own
	// backward-paging cursor.
	Events []*Event `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	// next_cursor is the opaque cursor for the next page. Empty if no more pages.
	NextCursor    []byte `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryStreamHistoryResponse) Reset() {
	*x = QueryStreamHistoryResponse{}
	mi := &file_holomush_plugin_host_v1_stream_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryStreamHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryStreamHistoryResponse) ProtoMessage() {}

func (x *QueryStreamHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_holomush_plugin_host_v1_stream_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryStreamHistoryResponse.ProtoReflect.Descriptor instead.
func (*QueryStreamHistoryResponse) Descriptor() ([]byte, []int) {
	return file_holomush_plugin_host_v1_stream_proto_rawDescGZIP(), []int{2}
}

func (x *QueryStreamHistoryResponse) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *QueryStreamHistoryResponse) GetNextCursor() []byte {
	if x != nil {
		return x.NextCursor
	}
	return nil
}

// AddSessionStreamRequest is the (currently unserved, holomush-l6std) request to
// subscribe an active session to one more stream.
type AddSessionStreamRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Active session identifier.
	SessionId string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Stream name to subscribe to (format: "prefix:id").
	Stream string `protobuf:"bytes,2,opt,name=stream,proto3" json:"stream,omitempty"`
	// replay_mode controls initial replay. Optional; defaults to
	// FROM_CURSOR if unspecified for backwards compatibility.
	ReplayMode    StreamReplayMode `protobuf:"varint,3,opt,name=replay_mode,json=replayMode,proto3,enum=holomush.plugin.host.v1.StreamReplayMode" json:"replay_mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddSessionStreamRequest) Reset() {
	*x = AddSessionStreamRequest{}
	mi := &file_holomush_plugin_host_v1_stream_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddSessionStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddSessionStreamRequest) ProtoMessage() {}

func (x *AddSessionStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_holomush_plugin_host_v1_stream_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddSessionStreamRequest.ProtoReflect.Descriptor instead.
func (*AddSessionStreamRequest) Descriptor() ([]byte, []int) {
	return file_holomush_plugin_host_v1_stream_proto_rawDescGZIP(), []int{3}
}

func (x *AddSessionStreamRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AddSessionStreamRequest) GetStream() string {
	if x != nil {
		return x.Stream
	}
	return ""
}

func (x *AddSessionStreamRequest) GetReplayMode() StreamReplayMode {
	if x != nil {
		return x.ReplayMode
	}
	return StreamReplayMode_STREAM_REPLAY_MODE_UNSPECIFIED
}

// AddSessionStreamResponse is the empty ack for AddSessionStream (unserved,
// holomush-l6std).
type AddSessionStreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddSessionStreamResponse) Reset() {
	*x = AddSessionStreamResponse{}
	mi := &file_holomush_plugin_host_v1_stream_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddSessionStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddSessionStreamResponse) ProtoMessage() {}

func (x *AddSessionStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_holomush_plugin_host_v1_stream_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddSessionStreamResponse.ProtoReflect.Descriptor instead.
func (*AddSessionStreamResponse) Descriptor() ([]byte, []int) {
	return file_holomush_plugin_host_v1_stream_proto_rawDescGZIP(), []int{4}
}

// RemoveSessionStreamRequest is the (currently unserved, holomush-l6std) request
// to unsubscribe an active session from a stream.
type RemoveSessionStreamRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Active session identifier.
	SessionId string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Stream name to unsubscribe from (format: "prefix:id").
	Stream        string `protobuf:"bytes,2,opt,name=stream,proto3" json:"stream,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveSessionStreamRequest) Reset() {
	*x = RemoveSessionStreamRequest{}
	mi := &file_holomush_plugin_host_v1_stream_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveSessionStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveSessionStreamRequest) ProtoMessage() {}

func (x *RemoveSessionStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_holomush_plugin_host_v1_stream_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveSessionStreamRequest.ProtoReflect.Descriptor instead.
func (*RemoveSessionStreamRequest) Descriptor() ([]byte, []int) {
	return file_holomush_plugin_host_v1_stream_proto_rawDescGZIP(), []int{5}
}

func (x *RemoveSessionStreamRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RemoveSessionStreamRequest) GetStream() string {
	if x != nil {
		return x.Stream
	}
	return ""
}

// RemoveSessionStreamResponse is the empty ack for RemoveSessionStream
// (unserved, holomush-l6std).
type RemoveSessionStreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveSessionStreamResponse) Reset() {
	*x = RemoveSessionStreamResponse{}
	mi := &file_holomush_plugin_host_v1_stream_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveSessionStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveSessionStreamResponse) ProtoMessage() {}

func (x *RemoveSessionStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_holomush_plugin_host_v1_stream_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveSessionStreamResponse.ProtoReflect.Descriptor instead.
func (*RemoveSessionStreamResponse) Descriptor() ([]byte, []int) {
	return file_holomush_plugin_host_v1_stream_proto_rawDescGZIP(), []int{6}
}

var File_holomush_plugin_host_v1_stream_proto protoreflect.FileDescriptor

const file_holomush_plugin_host_v1_stream_proto_rawDesc = "" +
	"\n" +
	"$holomush/plugin/host/v1/stream.proto\x12\x17holomush.plugin.host.v1\x1a\x1bbuf/validate/validate.proto\"\x85\x02\n" +
	"\x05Event\x12\x17\n" +
	"\x02id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x02id\x12\x1f\n" +
	"\x06stream\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x06stream\x12\x1b\n" +
	"\x04type\x18\x03 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x04type\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x12&\n" +
	"\n" +
	"actor_kind\x18\x05 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\tactorKind\x12\"\n" +
	"\bactor_id\x18\x06 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\aactorId\x12#\n" +
	"\apayload\x18\a \x01(\tB\t\xbaH\x06r\x04\x18\x80\x80\x04R\apayload\x12\x16\n" +
	"\x06cursor\x18\b \x01(\fR\x06cursor\"\x8e\x01\n" +
	"\x19QueryStreamHistoryRequest\x12\x1f\n" +
	"\x06stream\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x06stream\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\x12\"\n" +
	"\rnot_before_ms\x18\x03 \x01(\x03R\vnotBeforeMs\x12\x16\n" +
	"\x06cursor\x18\x04 \x01(\fR\x06cursor\"u\n" +
	"\x1aQueryStreamHistoryResponse\x126\n" +
	"\x06events\x18\x01 \x03(\v2\x1e.holomush.plugin.host.v1.EventR\x06events\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\fR\n" +
	"nextCursor\"\xae\x01\n" +
	"\x17AddSessionStreamRequest\x12&\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\tsessionId\x12\x1f\n" +
	"\x06stream\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x06stream\x12J\n" +
	"\vreplay_mode\x18\x03 \x01(\x0e2).holomush.plugin.host.v1.StreamReplayModeR\n" +
	"replayMode\"\x1a\n" +
	"\x18AddSessionStreamResponse\"e\n" +
	"\x1aRemoveSessionStreamRequest\x12&\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\tsessionId\x12\x1f\n" +
	"\x06stream\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x06stream\"\x1d\n" +
	"\x1bRemoveSessionStreamResponse*|\n" +
	"\x10StreamReplayMode\x12\"\n" +
	"\x1eSTREAM_REPLAY_MODE_UNSPECIFIED\x10\x00\x12\"\n" +
	"\x1eSTREAM_REPLAY_MODE_FROM_CURSOR\x10\x01\x12 \n" +
	"\x1cSTREAM_REPLAY_MODE_LIVE_ONLY\x10\x022\x95\x01\n" +
	"\x14StreamHistoryService\x12}\n" +
	"\x12QueryStreamHistory\x122.holomush.plugin.host.v1.QueryStreamHistoryRequest\x1a3.holomush.plugin.host.v1.QueryStreamHistoryResponse2\x97\x02\n" +
	"\x19StreamSubscriptionService\x12w\n" +
	"\x10AddSessionStream\x120.holomush.plugin.host.v1.AddSessionStreamRequest\x1a1.holomush.plugin.host.v1.AddSessionStreamResponse\x12\x80\x01\n" +
	"\x13RemoveSessionStream\x123.holomush.plugin.host.v1.RemoveSessionStreamRequest\x1a4.holomush.plugin.host.v1.RemoveSessionStreamResponseB\xf0\x01\n" +
	"\x1bcom.holomush.plugin.host.v1B\vStreamProtoP\x01ZEgithub.com/holomush/holomush/pkg/proto/holomush/plugin/host/v1;hostv1\xa2\x02\x03HPH\xaa\x02\x17Holomush.Plugin.Host.V1\xca\x02\x17Holomush\\Plugin\\Host\\V1\xe2\x02#Holomush\\Plugin\\Host\\V1\\GPBMetadata\xea\x02\x1aHolomush::Plugin::Host::V1b\x06proto3"

var (
	file_holomush_plugin_host_v1_stream_proto_rawDescOnce sync.Once
	file_holomush_plugin_host_v1_stream_proto_rawDescData []byte
)

func file_holomush_plugin_host_v1_stream_proto_rawDescGZIP() []byte {
	file_holomush_plugin_host_v1_stream_proto_rawDescOnce.Do(func() {
		file_holomush_plugin_host_v1_stream_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_holomush_plugin_host_v1_stream_proto_rawDesc), len(file_holomush_plugin_host_v1_stream_proto_rawDesc)))
	})
	return file_holomush_plugin_host_v1_stream_proto_rawDescData
}

var file_holomush_plugin_host_v1_stream_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_holomush_plugin_host_v1_stream_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_holomush_plugin_host_v1_stream_proto_goTypes = []any{
	(StreamReplayMode)(0),               // 0: holomush.plugin.host.v1.StreamReplayMode
	(*Event)(nil),                       // 1: holomush.plugin.host.v1.Event
	(*QueryStreamHistoryRequest)(nil),   // 2: holomush.plugin.host.v1.QueryStreamHistoryRequest
	(*QueryStreamHistoryResponse)(nil),  // 3: holomush.plugin.host.v1.QueryStreamHistoryResponse
	(*AddSessionStreamRequest)(nil),     // 4: holomush.plugin.host.v1.AddSessionStreamRequest
	(*AddSessionStreamResponse)(nil),    // 5: holomush.plugin.host.v1.AddSessionStreamResponse
	(*RemoveSessionStreamRequest)(nil),  // 6: holomush.plugin.host.v1.RemoveSessionStreamRequest
	(*RemoveSessionStreamResponse)(nil), // 7: holomush.plugin.host.v1.RemoveSessionStreamResponse
}
var file_holomush_plugin_host_v1_stream_proto_depIdxs = []int32{
	1, // 0: holomush.plugin.host.v1.QueryStreamHistoryResponse.events:type_name -> holomush.plugin.host.v1.Event
	0, // 1: holomush.plugin.host.v1.AddSessionStreamRequest.replay_mode:type_name -> holomush.plugin.host.v1.StreamReplayMode
	2, // 2: holomush.plugin.host.v1.StreamHistoryService.QueryStreamHistory:input_type -> holomush.plugin.host.v1.QueryStreamHistoryRequest
	4, // 3: holomush.plugin.host.v1.StreamSubscriptionService.AddSessionStream:input_type -> holomush.plugin.host.v1.AddSessionStreamRequest
	6, // 4: holomush.plugin.host.v1.StreamSubscriptionService.RemoveSessionStream:input_type -> holomush.plugin.host.v1.RemoveSessionStreamRequest
	3, // 5: holomush.plugin.host.v1.StreamHistoryService.QueryStreamHistory:output_type -> holomush.plugin.host.v1.QueryStreamHistoryResponse
	5, // 6: holomush.plugin.host.v1.StreamSubscriptionService.AddSessionStream:output_type -> holomush.plugin.host.v1.AddSessionStreamResponse
	7, // 7: holomush.plugin.host.v1.StreamSubscriptionService.RemoveSessionStream:output_type -> holomush.plugin.host.v1.RemoveSessionStreamResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_holomush_plugin_host_v1_stream_proto_init() }
func file_holomush_plugin_host_v1_stream_proto_init() {
	if File_holomush_plugin_host_v1_stream_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_holomush_plugin_host_v1_stream_proto_rawDesc), len(file_holomush_plugin_host_v1_stream_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_holomush_plugin_host_v1_stream_proto_goTypes,
		DependencyIndexes: file_holomush_plugin_host_v1_stream_proto_depIdxs,
		EnumInfos:         file_holomush_plugin_host_v1_stream_proto_enumTypes,
		MessageInfos:      file_holomush_plugin_host_v1_stream_proto_msgTypes,
	}.Build()
	File_holomush_plugin_host_v1_stream_proto = out.File
	file_holomush_plugin_host_v1_stream_proto_goTypes = nil
	file_holomush_plugin_host_v1_stream_proto_depIdxs = nil
}
