// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 HoloMUSH Contributors

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: holomush/admin/v1/admin.proto

package adminv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/holomush/holomush/pkg/proto/holomush/admin/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// AdminServiceName is the fully-qualified name of the AdminService service.
	AdminServiceName = "holomush.admin.v1.AdminService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AdminServiceStatusProcedure is the fully-qualified name of the AdminService's Status RPC.
	AdminServiceStatusProcedure = "/holomush.admin.v1.AdminService/Status"
	// AdminServiceAuthenticateProcedure is the fully-qualified name of the AdminService's Authenticate
	// RPC.
	AdminServiceAuthenticateProcedure = "/holomush.admin.v1.AdminService/Authenticate"
	// AdminServiceApproveProcedure is the fully-qualified name of the AdminService's Approve RPC.
	AdminServiceApproveProcedure = "/holomush.admin.v1.AdminService/Approve"
	// AdminServiceResetTOTPProcedure is the fully-qualified name of the AdminService's ResetTOTP RPC.
	AdminServiceResetTOTPProcedure = "/holomush.admin.v1.AdminService/ResetTOTP"
)

// AdminServiceClient is a client for the holomush.admin.v1.AdminService service.
type AdminServiceClient interface {
	// Status returns the admin-socket server's liveness state and binary version.
	Status(context.Context, *connect.Request[v1.StatusRequest]) (*connect.Response[v1.StatusResponse], error)
	// Authenticate verifies operator credentials + TOTP and returns a
	// short-lived (10 min) session token for use in Approve and ResetTOTP.
	// Spec §3 wire surface; INV-D1, INV-D2.
	Authenticate(context.Context, *connect.Request[v1.AuthenticateRequest]) (*connect.Response[v1.AuthenticateResponse], error)
	// Approve is the second-op signoff on a pending admin_approvals row.
	// Spec §3, §6 Approve flow; INV-D5, INV-D6, INV-D7.
	Approve(context.Context, *connect.Request[v1.ApproveRequest]) (*connect.Response[v1.ApproveResponse], error)
	// ResetTOTP clears a target player's TOTP enrollment and emits a
	// crypto.totp_cleared audit event with cleared_by="admin_reset".
	// Spec §3, §4 reset flow.
	ResetTOTP(context.Context, *connect.Request[v1.ResetTOTPRequest]) (*connect.Response[v1.ResetTOTPResponse], error)
}

// NewAdminServiceClient constructs a client for the holomush.admin.v1.AdminService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAdminServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AdminServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	adminServiceMethods := v1.File_holomush_admin_v1_admin_proto.Services().ByName("AdminService").Methods()
	return &adminServiceClient{
		status: connect.NewClient[v1.StatusRequest, v1.StatusResponse](
			httpClient,
			baseURL+AdminServiceStatusProcedure,
			connect.WithSchema(adminServiceMethods.ByName("Status")),
			connect.WithClientOptions(opts...),
		),
		authenticate: connect.NewClient[v1.AuthenticateRequest, v1.AuthenticateResponse](
			httpClient,
			baseURL+AdminServiceAuthenticateProcedure,
			connect.WithSchema(adminServiceMethods.ByName("Authenticate")),
			connect.WithClientOptions(opts...),
		),
		approve: connect.NewClient[v1.ApproveRequest, v1.ApproveResponse](
			httpClient,
			baseURL+AdminServiceApproveProcedure,
			connect.WithSchema(adminServiceMethods.ByName("Approve")),
			connect.WithClientOptions(opts...),
		),
		resetTOTP: connect.NewClient[v1.ResetTOTPRequest, v1.ResetTOTPResponse](
			httpClient,
			baseURL+AdminServiceResetTOTPProcedure,
			connect.WithSchema(adminServiceMethods.ByName("ResetTOTP")),
			connect.WithClientOptions(opts...),
		),
	}
}

// adminServiceClient implements AdminServiceClient.
type adminServiceClient struct {
	status       *connect.Client[v1.StatusRequest, v1.StatusResponse]
	authenticate *connect.Client[v1.AuthenticateRequest, v1.AuthenticateResponse]
	approve      *connect.Client[v1.ApproveRequest, v1.ApproveResponse]
	resetTOTP    *connect.Client[v1.ResetTOTPRequest, v1.ResetTOTPResponse]
}

// Status calls holomush.admin.v1.AdminService.Status.
func (c *adminServiceClient) Status(ctx context.Context, req *connect.Request[v1.StatusRequest]) (*connect.Response[v1.StatusResponse], error) {
	return c.status.CallUnary(ctx, req)
}

// Authenticate calls holomush.admin.v1.AdminService.Authenticate.
func (c *adminServiceClient) Authenticate(ctx context.Context, req *connect.Request[v1.AuthenticateRequest]) (*connect.Response[v1.AuthenticateResponse], error) {
	return c.authenticate.CallUnary(ctx, req)
}

// Approve calls holomush.admin.v1.AdminService.Approve.
func (c *adminServiceClient) Approve(ctx context.Context, req *connect.Request[v1.ApproveRequest]) (*connect.Response[v1.ApproveResponse], error) {
	return c.approve.CallUnary(ctx, req)
}

// ResetTOTP calls holomush.admin.v1.AdminService.ResetTOTP.
func (c *adminServiceClient) ResetTOTP(ctx context.Context, req *connect.Request[v1.ResetTOTPRequest]) (*connect.Response[v1.ResetTOTPResponse], error) {
	return c.resetTOTP.CallUnary(ctx, req)
}

// AdminServiceHandler is an implementation of the holomush.admin.v1.AdminService service.
type AdminServiceHandler interface {
	// Status returns the admin-socket server's liveness state and binary version.
	Status(context.Context, *connect.Request[v1.StatusRequest]) (*connect.Response[v1.StatusResponse], error)
	// Authenticate verifies operator credentials + TOTP and returns a
	// short-lived (10 min) session token for use in Approve and ResetTOTP.
	// Spec §3 wire surface; INV-D1, INV-D2.
	Authenticate(context.Context, *connect.Request[v1.AuthenticateRequest]) (*connect.Response[v1.AuthenticateResponse], error)
	// Approve is the second-op signoff on a pending admin_approvals row.
	// Spec §3, §6 Approve flow; INV-D5, INV-D6, INV-D7.
	Approve(context.Context, *connect.Request[v1.ApproveRequest]) (*connect.Response[v1.ApproveResponse], error)
	// ResetTOTP clears a target player's TOTP enrollment and emits a
	// crypto.totp_cleared audit event with cleared_by="admin_reset".
	// Spec §3, §4 reset flow.
	ResetTOTP(context.Context, *connect.Request[v1.ResetTOTPRequest]) (*connect.Response[v1.ResetTOTPResponse], error)
}

// NewAdminServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAdminServiceHandler(svc AdminServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	adminServiceMethods := v1.File_holomush_admin_v1_admin_proto.Services().ByName("AdminService").Methods()
	adminServiceStatusHandler := connect.NewUnaryHandler(
		AdminServiceStatusProcedure,
		svc.Status,
		connect.WithSchema(adminServiceMethods.ByName("Status")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceAuthenticateHandler := connect.NewUnaryHandler(
		AdminServiceAuthenticateProcedure,
		svc.Authenticate,
		connect.WithSchema(adminServiceMethods.ByName("Authenticate")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceApproveHandler := connect.NewUnaryHandler(
		AdminServiceApproveProcedure,
		svc.Approve,
		connect.WithSchema(adminServiceMethods.ByName("Approve")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceResetTOTPHandler := connect.NewUnaryHandler(
		AdminServiceResetTOTPProcedure,
		svc.ResetTOTP,
		connect.WithSchema(adminServiceMethods.ByName("ResetTOTP")),
		connect.WithHandlerOptions(opts...),
	)
	return "/holomush.admin.v1.AdminService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AdminServiceStatusProcedure:
			adminServiceStatusHandler.ServeHTTP(w, r)
		case AdminServiceAuthenticateProcedure:
			adminServiceAuthenticateHandler.ServeHTTP(w, r)
		case AdminServiceApproveProcedure:
			adminServiceApproveHandler.ServeHTTP(w, r)
		case AdminServiceResetTOTPProcedure:
			adminServiceResetTOTPHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAdminServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAdminServiceHandler struct{}

func (UnimplementedAdminServiceHandler) Status(context.Context, *connect.Request[v1.StatusRequest]) (*connect.Response[v1.StatusResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("holomush.admin.v1.AdminService.Status is not implemented"))
}

func (UnimplementedAdminServiceHandler) Authenticate(context.Context, *connect.Request[v1.AuthenticateRequest]) (*connect.Response[v1.AuthenticateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("holomush.admin.v1.AdminService.Authenticate is not implemented"))
}

func (UnimplementedAdminServiceHandler) Approve(context.Context, *connect.Request[v1.ApproveRequest]) (*connect.Response[v1.ApproveResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("holomush.admin.v1.AdminService.Approve is not implemented"))
}

func (UnimplementedAdminServiceHandler) ResetTOTP(context.Context, *connect.Request[v1.ResetTOTPRequest]) (*connect.Response[v1.ResetTOTPResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("holomush.admin.v1.AdminService.ResetTOTP is not implemented"))
}
