// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	plugins "github.com/holomush/holomush/internal/plugin"
	mock "github.com/stretchr/testify/mock"

	pluginsdk "github.com/holomush/holomush/pkg/plugin"
)

// MockHost is an autogenerated mock type for the Host type
type MockHost struct {
	mock.Mock
}

type MockHost_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHost) EXPECT() *MockHost_Expecter {
	return &MockHost_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with given fields: ctx
func (_m *MockHost) Close(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockHost_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockHost_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockHost_Expecter) Close(ctx interface{}) *MockHost_Close_Call {
	return &MockHost_Close_Call{Call: _e.mock.On("Close", ctx)}
}

func (_c *MockHost_Close_Call) Run(run func(ctx context.Context)) *MockHost_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockHost_Close_Call) Return(_a0 error) *MockHost_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHost_Close_Call) RunAndReturn(run func(context.Context) error) *MockHost_Close_Call {
	_c.Call.Return(run)
	return _c
}

// DeliverEvent provides a mock function with given fields: ctx, name, event
func (_m *MockHost) DeliverEvent(ctx context.Context, name string, event pluginsdk.Event) ([]pluginsdk.EmitEvent, error) {
	ret := _m.Called(ctx, name, event)

	if len(ret) == 0 {
		panic("no return value specified for DeliverEvent")
	}

	var r0 []pluginsdk.EmitEvent
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, pluginsdk.Event) ([]pluginsdk.EmitEvent, error)); ok {
		return rf(ctx, name, event)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, pluginsdk.Event) []pluginsdk.EmitEvent); ok {
		r0 = rf(ctx, name, event)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]pluginsdk.EmitEvent)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, pluginsdk.Event) error); ok {
		r1 = rf(ctx, name, event)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockHost_DeliverEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeliverEvent'
type MockHost_DeliverEvent_Call struct {
	*mock.Call
}

// DeliverEvent is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - event pluginsdk.Event
func (_e *MockHost_Expecter) DeliverEvent(ctx interface{}, name interface{}, event interface{}) *MockHost_DeliverEvent_Call {
	return &MockHost_DeliverEvent_Call{Call: _e.mock.On("DeliverEvent", ctx, name, event)}
}

func (_c *MockHost_DeliverEvent_Call) Run(run func(ctx context.Context, name string, event pluginsdk.Event)) *MockHost_DeliverEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(pluginsdk.Event))
	})
	return _c
}

func (_c *MockHost_DeliverEvent_Call) Return(_a0 []pluginsdk.EmitEvent, _a1 error) *MockHost_DeliverEvent_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockHost_DeliverEvent_Call) RunAndReturn(run func(context.Context, string, pluginsdk.Event) ([]pluginsdk.EmitEvent, error)) *MockHost_DeliverEvent_Call {
	_c.Call.Return(run)
	return _c
}

// Load provides a mock function with given fields: ctx, manifest, dir
func (_m *MockHost) Load(ctx context.Context, manifest *plugins.Manifest, dir string) error {
	ret := _m.Called(ctx, manifest, dir)

	if len(ret) == 0 {
		panic("no return value specified for Load")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *plugins.Manifest, string) error); ok {
		r0 = rf(ctx, manifest, dir)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockHost_Load_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Load'
type MockHost_Load_Call struct {
	*mock.Call
}

// Load is a helper method to define mock.On call
//   - ctx context.Context
//   - manifest *plugins.Manifest
//   - dir string
func (_e *MockHost_Expecter) Load(ctx interface{}, manifest interface{}, dir interface{}) *MockHost_Load_Call {
	return &MockHost_Load_Call{Call: _e.mock.On("Load", ctx, manifest, dir)}
}

func (_c *MockHost_Load_Call) Run(run func(ctx context.Context, manifest *plugins.Manifest, dir string)) *MockHost_Load_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*plugins.Manifest), args[2].(string))
	})
	return _c
}

func (_c *MockHost_Load_Call) Return(_a0 error) *MockHost_Load_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHost_Load_Call) RunAndReturn(run func(context.Context, *plugins.Manifest, string) error) *MockHost_Load_Call {
	_c.Call.Return(run)
	return _c
}

// Plugins provides a mock function with no fields
func (_m *MockHost) Plugins() []string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Plugins")
	}

	var r0 []string
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}

// MockHost_Plugins_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Plugins'
type MockHost_Plugins_Call struct {
	*mock.Call
}

// Plugins is a helper method to define mock.On call
func (_e *MockHost_Expecter) Plugins() *MockHost_Plugins_Call {
	return &MockHost_Plugins_Call{Call: _e.mock.On("Plugins")}
}

func (_c *MockHost_Plugins_Call) Run(run func()) *MockHost_Plugins_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockHost_Plugins_Call) Return(_a0 []string) *MockHost_Plugins_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHost_Plugins_Call) RunAndReturn(run func() []string) *MockHost_Plugins_Call {
	_c.Call.Return(run)
	return _c
}

// Unload provides a mock function with given fields: ctx, name
func (_m *MockHost) Unload(ctx context.Context, name string) error {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for Unload")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockHost_Unload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unload'
type MockHost_Unload_Call struct {
	*mock.Call
}

// Unload is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockHost_Expecter) Unload(ctx interface{}, name interface{}) *MockHost_Unload_Call {
	return &MockHost_Unload_Call{Call: _e.mock.On("Unload", ctx, name)}
}

func (_c *MockHost_Unload_Call) Run(run func(ctx context.Context, name string)) *MockHost_Unload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockHost_Unload_Call) Return(_a0 error) *MockHost_Unload_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHost_Unload_Call) RunAndReturn(run func(context.Context, string) error) *MockHost_Unload_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockHost creates a new instance of MockHost. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHost(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHost {
	mock := &MockHost{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
