// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	plugins "github.com/holomush/holomush/internal/plugin"
	mock "github.com/stretchr/testify/mock"
)

// MockManagerOption is an autogenerated mock type for the ManagerOption type
type MockManagerOption struct {
	mock.Mock
}

type MockManagerOption_Expecter struct {
	mock *mock.Mock
}

func (_m *MockManagerOption) EXPECT() *MockManagerOption_Expecter {
	return &MockManagerOption_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: _a0
func (_m *MockManagerOption) Execute(_a0 *plugins.Manager) {
	_m.Called(_a0)
}

// MockManagerOption_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockManagerOption_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - _a0 *plugins.Manager
func (_e *MockManagerOption_Expecter) Execute(_a0 interface{}) *MockManagerOption_Execute_Call {
	return &MockManagerOption_Execute_Call{Call: _e.mock.On("Execute", _a0)}
}

func (_c *MockManagerOption_Execute_Call) Run(run func(_a0 *plugins.Manager)) *MockManagerOption_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*plugins.Manager))
	})
	return _c
}

func (_c *MockManagerOption_Execute_Call) Return() *MockManagerOption_Execute_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockManagerOption_Execute_Call) RunAndReturn(run func(*plugins.Manager)) *MockManagerOption_Execute_Call {
	_c.Run(run)
	return _c
}

// NewMockManagerOption creates a new instance of MockManagerOption. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockManagerOption(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockManagerOption {
	mock := &MockManagerOption{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
