// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 HoloMUSH Contributors

// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file holomush/plugin/host/v1/audit.proto (package holomush.plugin.host.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { AuditRow, RowResult } from "../../v1/audit_pb";
import { file_holomush_plugin_v1_audit } from "../../v1/audit_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file holomush/plugin/host/v1/audit.proto.
 */
export const file_holomush_plugin_host_v1_audit: GenFile = /*@__PURE__*/
  fileDesc("CiNob2xvbXVzaC9wbHVnaW4vaG9zdC92MS9hdWRpdC5wcm90bxIXaG9sb211c2gucGx1Z2luLmhvc3QudjEiSAoaRGVjcnlwdE93bkF1ZGl0Um93c1JlcXVlc3QSKgoEcm93cxgBIAMoCzIcLmhvbG9tdXNoLnBsdWdpbi52MS5BdWRpdFJvdyJNChtEZWNyeXB0T3duQXVkaXRSb3dzUmVzcG9uc2USLgoHcmVzdWx0cxgBIAMoCzIdLmhvbG9tdXNoLnBsdWdpbi52MS5Sb3dSZXN1bHQykQEKDEF1ZGl0U2VydmljZRKAAQoTRGVjcnlwdE93bkF1ZGl0Um93cxIzLmhvbG9tdXNoLnBsdWdpbi5ob3N0LnYxLkRlY3J5cHRPd25BdWRpdFJvd3NSZXF1ZXN0GjQuaG9sb211c2gucGx1Z2luLmhvc3QudjEuRGVjcnlwdE93bkF1ZGl0Um93c1Jlc3BvbnNlQkdaRWdpdGh1Yi5jb20vaG9sb211c2gvaG9sb211c2gvcGtnL3Byb3RvL2hvbG9tdXNoL3BsdWdpbi9ob3N0L3YxO2hvc3R2MWIGcHJvdG8z", [file_holomush_plugin_v1_audit]);

/**
 * DecryptOwnAuditRowsRequest carries the calling plugin's OWN audit rows for
 * host-side read-back decryption. The host enforces OwnerMap subject ownership
 * (g1) per row; rows whose subject is owned by a different plugin are refused
 * with not_owner and never decrypted. The batch is REJECTED (not clamped) when
 * it exceeds the server-side cap of 500.
 *
 * @generated from message holomush.plugin.host.v1.DecryptOwnAuditRowsRequest
 */
export type DecryptOwnAuditRowsRequest = Message<"holomush.plugin.host.v1.DecryptOwnAuditRowsRequest"> & {
  /**
   * rows is the batch of audit rows to decrypt. Each row MUST have been
   * previously stored by this plugin (subject ownership enforced by the
   * host's OwnerMap g1 gate). A batch exceeding 500 rows is rejected
   * outright rather than partially processed.
   *
   * @generated from field: repeated holomush.plugin.v1.AuditRow rows = 1;
   */
  rows: AuditRow[];
};

/**
 * Describes the message holomush.plugin.host.v1.DecryptOwnAuditRowsRequest.
 * Use `create(DecryptOwnAuditRowsRequestSchema)` to create a new message.
 */
export const DecryptOwnAuditRowsRequestSchema: GenMessage<DecryptOwnAuditRowsRequest> = /*@__PURE__*/
  messageDesc(file_holomush_plugin_host_v1_audit, 0);

/**
 * DecryptOwnAuditRowsResponse returns one RowResult per request row, in the
 * same order (1:1 positional correspondence, INV-CRYPTO-37).
 *
 * @generated from message holomush.plugin.host.v1.DecryptOwnAuditRowsResponse
 */
export type DecryptOwnAuditRowsResponse = Message<"holomush.plugin.host.v1.DecryptOwnAuditRowsResponse"> & {
  /**
   * results contains one outcome per request row, in the same order as
   * DecryptOwnAuditRowsRequest.rows. Positional correspondence is
   * guaranteed (INV-CRYPTO-37); callers correlate by index or by RowResult.id.
   *
   * @generated from field: repeated holomush.plugin.v1.RowResult results = 1;
   */
  results: RowResult[];
};

/**
 * Describes the message holomush.plugin.host.v1.DecryptOwnAuditRowsResponse.
 * Use `create(DecryptOwnAuditRowsResponseSchema)` to create a new message.
 */
export const DecryptOwnAuditRowsResponseSchema: GenMessage<DecryptOwnAuditRowsResponse> = /*@__PURE__*/
  messageDesc(file_holomush_plugin_host_v1_audit, 1);

/**
 * AuditService is the host-brokered `audit` capability: a plugin asks the host
 * to decrypt a batch of its OWN encrypted audit rows host-side; the plugin
 * never holds a DEK. Carved from the former PluginHostService
 * (holomush-eykuh.1). Served by auditServer in
 * internal/plugin/goplugin/host_capability_servers.go.
 *
 * @generated from service holomush.plugin.host.v1.AuditService
 */
export const AuditService: GenService<{
  /**
   * DecryptOwnAuditRows decrypts a batch of the calling plugin's OWN encrypted
   * audit rows host-side; the plugin never holds a DEK, via ReadbackDecryptor.
   * DecryptOwnRows. Authorization is two-gate (INV-CRYPTO-27): OwnerMap subject
   * ownership (g1) plus the crypto.emits[].readback manifest flag (g2). Each
   * input row gets an independent RowResult (INV-CRYPTO-37) carrying either
   * plaintext or a stable snake_case no_plaintext_reason ("not_owner",
   * "auth_guard_deny", "dek_missing", "downgrade_refused", "stale_dek",
   * "audit_queue_full", "internal"; readback.go reasonToWire).
   *
   * @generated from rpc holomush.plugin.host.v1.AuditService.DecryptOwnAuditRows
   */
  decryptOwnAuditRows: {
    methodKind: "unary";
    input: typeof DecryptOwnAuditRowsRequestSchema;
    output: typeof DecryptOwnAuditRowsResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_holomush_plugin_host_v1_audit, 0);

