// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 HoloMUSH Contributors

// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts"
// @generated from file holomush/plugin/host/v1/emit.proto (package holomush.plugin.host.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { EmitEventRequest, EmitEventResponse, RegisterEmitTypeRequest, RegisterEmitTypeResponse, RequestEmitTokenRequest, RequestEmitTokenResponse } from "./emit_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * EmitService is the host-brokered `emit` capability: a plugin publishes
 * events through the host emit fence, requests the self-token a plugin-served
 * gRPC handler needs to do so, and registers the emit-type set the host
 * validates against the manifest. Carved from the former PluginHostService
 * (holomush-eykuh.1). Served by emitServer in
 * internal/plugin/goplugin/host_capability_servers.go.
 *
 * @generated from service holomush.plugin.host.v1.EmitService
 */
export const EmitService = {
  typeName: "holomush.plugin.host.v1.EmitService",
  methods: {
    /**
     * EmitEvent publishes one plugin-originated event onto the bus through the
     * host emit fence. The caller's identity is NOT trusted from the wire — the
     * plugin presents a host-issued dispatch token in the x-holomush-emit-token
     * metadata header, the host recovers the vouched-for actor from
     * tokenStore.Lookup(pluginName, token), and a missing/foreign token is
     * rejected (EMIT_TOKEN_MISSING / EMIT_TOKEN_REJECTED). The recovered actor
     * then flows through PluginEventEmitter.Emit, which enforces the manifest
     * gates: emits (subject namespace must be declared), actor_kinds_claimable
     * (actor kind must be listed — EMIT_ACTOR_KIND_NOT_CLAIMABLE), and the
     * crypto.emits sensitivity fence. These gates fire identically for Lua and
     * binary plugins (plugin runtime symmetry); the token mechanism is the
     * binary-side forgery fence.
     *
     * @generated from rpc holomush.plugin.host.v1.EmitService.EmitEvent
     */
    emitEvent: {
      name: "EmitEvent",
      I: EmitEventRequest,
      O: EmitEventResponse,
      kind: MethodKind.Unary,
    },
    /**
     * RequestEmitToken issues a self-token bound to {ActorPlugin, pluginName} so
     * a plugin-served gRPC handler (e.g. SceneService.CreateScene) — which is NOT
     * reached via DeliverEvent/DeliverCommand and so holds no dispatch token —
     * can still call EmitEvent. The plugin's identity is taken from the
     * mTLS-bound server struct (s.pluginName); the request carries no identity
     * fields, so a plugin cannot impersonate another actor or escalate to a
     * character actor through this RPC. The actor_kinds_claimable manifest gate
     * still fires when the issued token is later spent at EmitEvent.
     * (Spec §3.3.5 / §5.4 two-token pattern.)
     *
     * @generated from rpc holomush.plugin.host.v1.EmitService.RequestEmitToken
     */
    requestEmitToken: {
      name: "RequestEmitToken",
      I: RequestEmitTokenRequest,
      O: RequestEmitTokenResponse,
      kind: MethodKind.Unary,
    },
    /**
     * RegisterEmitType records one plugin-owned event type the plugin may later
     * emit, validated by the host against the manifest's crypto.emits per
     * INV-PLUGIN-32. Promotes the Lua holomush.register_emit_type(type) host
     * function (internal/plugin/hostfunc/stdlib_emit_registry.go) to the binary
     * surface so both runtimes declare their emit-type set through one channel.
     *
     * @generated from rpc holomush.plugin.host.v1.EmitService.RegisterEmitType
     */
    registerEmitType: {
      name: "RegisterEmitType",
      I: RegisterEmitTypeRequest,
      O: RegisterEmitTypeResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

