// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 HoloMUSH Contributors

// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts"
// @generated from file holomush/plugin/host/v1/kv.proto (package holomush.plugin.host.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { DeleteRequest, DeleteResponse, GetRequest, GetResponse, SetRequest, SetResponse } from "./kv_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * KVService is the host-brokered `kv` capability: a plugin reads, writes, and
 * deletes keys in its own namespaced key-value store. The namespace is the
 * CALLING plugin's identity, bound host-side from the authenticated transport
 * (mirroring the sibling host services) — it is NOT a request field, so one
 * plugin can never target another plugin's KV partition. Carved from the former
 * PluginHostService (holomush-eykuh.1). All three RPCs are DECLARED BUT UNSERVED
 * today (holomush-l6std): no server impl, no production client; they return
 * codes.Unimplemented.
 *
 * @generated from service holomush.plugin.host.v1.KVService
 */
export const KVService = {
  typeName: "holomush.plugin.host.v1.KVService",
  methods: {
    /**
     * Get reads a value from the plugin's namespaced key-value store.
     * DECLARED BUT UNSERVED (holomush-l6std): no server impl, no client; returns
     * codes.Unimplemented today.
     *
     * @generated from rpc holomush.plugin.host.v1.KVService.Get
     */
    get: {
      name: "Get",
      I: GetRequest,
      O: GetResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Set writes a value into the plugin's namespaced key-value store.
     * DECLARED BUT UNSERVED (holomush-l6std): no server impl, no client; returns
     * codes.Unimplemented today.
     *
     * @generated from rpc holomush.plugin.host.v1.KVService.Set
     */
    set: {
      name: "Set",
      I: SetRequest,
      O: SetResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Delete removes a key from the plugin's namespaced key-value store.
     * DECLARED BUT UNSERVED (holomush-l6std): no server impl, no client; returns
     * codes.Unimplemented today.
     *
     * @generated from rpc holomush.plugin.host.v1.KVService.Delete
     */
    delete: {
      name: "Delete",
      I: DeleteRequest,
      O: DeleteResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

