// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	ulid "github.com/oklog/ulid/v2"
	mock "github.com/stretchr/testify/mock"

	world "github.com/holomush/holomush/internal/world"
)

// MockCharacterRepository is an autogenerated mock type for the CharacterRepository type
type MockCharacterRepository struct {
	mock.Mock
}

type MockCharacterRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCharacterRepository) EXPECT() *MockCharacterRepository_Expecter {
	return &MockCharacterRepository_Expecter{mock: &_m.Mock}
}

// CountByPlayer provides a mock function with given fields: ctx, playerID
func (_m *MockCharacterRepository) CountByPlayer(ctx context.Context, playerID ulid.ULID) (int, error) {
	ret := _m.Called(ctx, playerID)

	if len(ret) == 0 {
		panic("no return value specified for CountByPlayer")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ulid.ULID) (int, error)); ok {
		return rf(ctx, playerID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ulid.ULID) int); ok {
		r0 = rf(ctx, playerID)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, ulid.ULID) error); ok {
		r1 = rf(ctx, playerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCharacterRepository_CountByPlayer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountByPlayer'
type MockCharacterRepository_CountByPlayer_Call struct {
	*mock.Call
}

// CountByPlayer is a helper method to define mock.On call
//   - ctx context.Context
//   - playerID ulid.ULID
func (_e *MockCharacterRepository_Expecter) CountByPlayer(ctx interface{}, playerID interface{}) *MockCharacterRepository_CountByPlayer_Call {
	return &MockCharacterRepository_CountByPlayer_Call{Call: _e.mock.On("CountByPlayer", ctx, playerID)}
}

func (_c *MockCharacterRepository_CountByPlayer_Call) Run(run func(ctx context.Context, playerID ulid.ULID)) *MockCharacterRepository_CountByPlayer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(ulid.ULID))
	})
	return _c
}

func (_c *MockCharacterRepository_CountByPlayer_Call) Return(_a0 int, _a1 error) *MockCharacterRepository_CountByPlayer_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCharacterRepository_CountByPlayer_Call) RunAndReturn(run func(context.Context, ulid.ULID) (int, error)) *MockCharacterRepository_CountByPlayer_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, char
func (_m *MockCharacterRepository) Create(ctx context.Context, char *world.Character) error {
	ret := _m.Called(ctx, char)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *world.Character) error); ok {
		r0 = rf(ctx, char)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCharacterRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockCharacterRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - char *world.Character
func (_e *MockCharacterRepository_Expecter) Create(ctx interface{}, char interface{}) *MockCharacterRepository_Create_Call {
	return &MockCharacterRepository_Create_Call{Call: _e.mock.On("Create", ctx, char)}
}

func (_c *MockCharacterRepository_Create_Call) Run(run func(ctx context.Context, char *world.Character)) *MockCharacterRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*world.Character))
	})
	return _c
}

func (_c *MockCharacterRepository_Create_Call) Return(_a0 error) *MockCharacterRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCharacterRepository_Create_Call) RunAndReturn(run func(context.Context, *world.Character) error) *MockCharacterRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// ExistsByName provides a mock function with given fields: ctx, name
func (_m *MockCharacterRepository) ExistsByName(ctx context.Context, name string) (bool, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for ExistsByName")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, name)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCharacterRepository_ExistsByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExistsByName'
type MockCharacterRepository_ExistsByName_Call struct {
	*mock.Call
}

// ExistsByName is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockCharacterRepository_Expecter) ExistsByName(ctx interface{}, name interface{}) *MockCharacterRepository_ExistsByName_Call {
	return &MockCharacterRepository_ExistsByName_Call{Call: _e.mock.On("ExistsByName", ctx, name)}
}

func (_c *MockCharacterRepository_ExistsByName_Call) Run(run func(ctx context.Context, name string)) *MockCharacterRepository_ExistsByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockCharacterRepository_ExistsByName_Call) Return(_a0 bool, _a1 error) *MockCharacterRepository_ExistsByName_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCharacterRepository_ExistsByName_Call) RunAndReturn(run func(context.Context, string) (bool, error)) *MockCharacterRepository_ExistsByName_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCharacterRepository creates a new instance of MockCharacterRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCharacterRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCharacterRepository {
	mock := &MockCharacterRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
