// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 HoloMUSH Contributors

// @generated by protoc-gen-es v2.12.1 with parameter "target=ts"
// @generated from file holomush/characteraccess/v1/characteraccess.proto (package holomush.characteraccess.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_buf_validate_validate } from "../../../buf/validate/validate_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file holomush/characteraccess/v1/characteraccess.proto.
 */
export const file_holomush_characteraccess_v1_characteraccess: GenFile = /*@__PURE__*/
  fileDesc("CjFob2xvbXVzaC9jaGFyYWN0ZXJhY2Nlc3MvdjEvY2hhcmFjdGVyYWNjZXNzLnByb3RvEhtob2xvbXVzaC5jaGFyYWN0ZXJhY2Nlc3MudjEiSwoMUHJvZmlsZUltYWdlEhAKCG1lZGlhX2lkGAEgASgJEhAKCGFsdF90ZXh0GAIgASgJEhcKD2NvbnRlbnRfd2FybmluZxgDIAEoCSLEAgoPUHVibGljQ2hhcmFjdGVyEgoKAmlkGAEgASgJEgwKBG5hbWUYAiABKAkSEwoLZGVzY3JpcHRpb24YAyABKAkSSgoHcHJvZmlsZRgEIAMoCzI5LmhvbG9tdXNoLmNoYXJhY3RlcmFjY2Vzcy52MS5QdWJsaWNDaGFyYWN0ZXIuUHJvZmlsZUVudHJ5EkAKDXByaW1hcnlfaW1hZ2UYBSABKAsyKS5ob2xvbXVzaC5jaGFyYWN0ZXJhY2Nlc3MudjEuUHJvZmlsZUltYWdlEkQKB2dhbGxlcnkYBiADKAsyKS5ob2xvbXVzaC5jaGFyYWN0ZXJhY2Nlc3MudjEuUHJvZmlsZUltYWdlQgi6SAWSAQIQChouCgxQcm9maWxlRW50cnkSCwoDa2V5GAEgASgJEg0KBXZhbHVlGAIgASgJOgI4ASJQChpHZXRDaGFyYWN0ZXJQcm9maWxlUmVxdWVzdBIUCgxjaGFyYWN0ZXJfaWQYASABKAkSHAoUcGxheWVyX3Nlc3Npb25fdG9rZW4YAiABKAkiXgobR2V0Q2hhcmFjdGVyUHJvZmlsZVJlc3BvbnNlEj8KCWNoYXJhY3RlchgBIAEoCzIsLmhvbG9tdXNoLmNoYXJhY3RlcmFjY2Vzcy52MS5QdWJsaWNDaGFyYWN0ZXIyowEKFkNoYXJhY3RlckFjY2Vzc1NlcnZpY2USiAEKE0dldENoYXJhY3RlclByb2ZpbGUSNy5ob2xvbXVzaC5jaGFyYWN0ZXJhY2Nlc3MudjEuR2V0Q2hhcmFjdGVyUHJvZmlsZVJlcXVlc3QaOC5ob2xvbXVzaC5jaGFyYWN0ZXJhY2Nlc3MudjEuR2V0Q2hhcmFjdGVyUHJvZmlsZVJlc3BvbnNlQlZaVGdpdGh1Yi5jb20vaG9sb211c2gvaG9sb211c2gvcGtnL3Byb3RvL2hvbG9tdXNoL2NoYXJhY3RlcmFjY2Vzcy92MTtjaGFyYWN0ZXJhY2Nlc3N2MWIGcHJvdG8z", [file_buf_validate_validate]);

/**
 * ProfileImage is one stored image reference on a profile. The shape ships in
 * v0.13 so alt text and content warnings have somewhere to live before any
 * upload path exists; projectPublic
 * (internal/grpc/characteraccess_projection.go) emits none of these in v0.13,
 * because nothing in v0.13 mints a media identifier.
 *
 * @generated from message holomush.characteraccess.v1.ProfileImage
 */
export type ProfileImage = Message<"holomush.characteraccess.v1.ProfileImage"> & {
  /**
   * media_id is an opaque handle to stored bytes. Its format is deliberately
   * unfixed in v0.13 — no host code parses, validates or generates one.
   *
   * @generated from field: string media_id = 1;
   */
  mediaId: string;

  /**
   * alt_text is the operator-authored textual substitute a screen reader
   * announces in place of the image.
   *
   * @generated from field: string alt_text = 2;
   */
  altText: string;

  /**
   * content_warning is the advisory a client renders BEFORE revealing the
   * image, so a viewer can decline to see it.
   *
   * @generated from field: string content_warning = 3;
   */
  contentWarning: string;
};

/**
 * Describes the message holomush.characteraccess.v1.ProfileImage.
 * Use `create(ProfileImageSchema)` to create a new message.
 */
export const ProfileImageSchema: GenMessage<ProfileImage> = /*@__PURE__*/
  messageDesc(file_holomush_characteraccess_v1_characteraccess, 0);

/**
 * PublicCharacter is the character shape the `public` audience receives. It is
 * the only message projectPublic constructs, and it carries neither the owning
 * player's identifier nor the character's current location: an owner-only or
 * position-revealing value has no field to land in, so the absence is checked by
 * the Go compiler rather than by a handler remembering to clear a field.
 *
 * Those two field names are deliberately not spelled out here. A plan
 * acceptance criterion greps this file for them, and it must stay able to fail
 * on a field that was ADDED rather than on a comment describing what is absent.
 *
 * It carries no visibility hint, mask, flag map or hidden-field list either. A
 * value this viewer may not see is absent from the marshaled bytes, and the
 * client is not told a decision was made.
 *
 * @generated from message holomush.characteraccess.v1.PublicCharacter
 */
export type PublicCharacter = Message<"holomush.characteraccess.v1.PublicCharacter"> & {
  /**
   * id is the stable characters.id ULID the profile URL is keyed on; it
   * survives rename, which a name-keyed key would not.
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * name is the display name world.Service.GetCharacterDescription read from
   * characters.name, forwarded as the stored bytes with no normalization,
   * casefolding or re-encoding.
   *
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * description is the in-world `look` text (characters.description), gated by
   * the read_description action rather than by any per-attribute floor.
   *
   * @generated from field: string description = 3;
   */
  description: string;

  /**
   * profile holds the viewer-permitted `profile.*` attributes keyed by their
   * governed names. An attribute whose floor this viewer does not clear is
   * absent from the map, never present-and-empty.
   *
   * @generated from field: map<string, string> profile = 4;
   */
  profile: { [key: string]: string };

  /**
   * primary_image is the single `profile.image.primary` row when one is both
   * present and permitted. v0.13 always omits it.
   *
   * @generated from field: holomush.characteraccess.v1.ProfileImage primary_image = 5;
   */
  primaryImage?: ProfileImage | undefined;

  /**
   * gallery holds the permitted `profile.image.gallery.00`…`.09` rows, capped
   * at the ten names the storage schema fixes. v0.13 always leaves it empty.
   *
   * @generated from field: repeated holomush.characteraccess.v1.ProfileImage gallery = 6;
   */
  gallery: ProfileImage[];
};

/**
 * Describes the message holomush.characteraccess.v1.PublicCharacter.
 * Use `create(PublicCharacterSchema)` to create a new message.
 */
export const PublicCharacterSchema: GenMessage<PublicCharacter> = /*@__PURE__*/
  messageDesc(file_holomush_characteraccess_v1_characteraccess, 1);

/**
 * GetCharacterProfileRequest names the character to resolve and carries the
 * caller's optional session token.
 *
 * @generated from message holomush.characteraccess.v1.GetCharacterProfileRequest
 */
export type GetCharacterProfileRequest = Message<"holomush.characteraccess.v1.GetCharacterProfileRequest"> & {
  /**
   * character_id is the target character's ULID. A value that does not parse
   * takes the same opaque outcome as one that names no row.
   *
   * @generated from field: string character_id = 1;
   */
  characterId: string;

  /**
   * player_session_token is the raw session token the gateway lifted from the
   * X-Session-Token header. It is OPTIONAL: an empty, expired or otherwise
   * unresolvable value resolves the least-privileged rung rather than an
   * authentication error, so a logged-out visitor still reaches the public page.
   *
   * @generated from field: string player_session_token = 2;
   */
  playerSessionToken: string;
};

/**
 * Describes the message holomush.characteraccess.v1.GetCharacterProfileRequest.
 * Use `create(GetCharacterProfileRequestSchema)` to create a new message.
 */
export const GetCharacterProfileRequestSchema: GenMessage<GetCharacterProfileRequest> = /*@__PURE__*/
  messageDesc(file_holomush_characteraccess_v1_characteraccess, 2);

/**
 * GetCharacterProfileResponse carries the projected profile.
 *
 * @generated from message holomush.characteraccess.v1.GetCharacterProfileResponse
 */
export type GetCharacterProfileResponse = Message<"holomush.characteraccess.v1.GetCharacterProfileResponse"> & {
  /**
   * character is the projection projectPublic built for this viewer.
   *
   * @generated from field: holomush.characteraccess.v1.PublicCharacter character = 1;
   */
  character?: PublicCharacter | undefined;
};

/**
 * Describes the message holomush.characteraccess.v1.GetCharacterProfileResponse.
 * Use `create(GetCharacterProfileResponseSchema)` to create a new message.
 */
export const GetCharacterProfileResponseSchema: GenMessage<GetCharacterProfileResponse> = /*@__PURE__*/
  messageDesc(file_holomush_characteraccess_v1_characteraccess, 3);

/**
 * CharacterAccessService is the host-side facade for the web character surface.
 * It constructs the viewer principal itself — resolving the optional player
 * session token through auth.PlayerSessionRepository and auth.PlayerRepository —
 * and owns every reachability and per-attribute visibility decision, so the
 * gateway proxies bytes and computes nothing.
 *
 * Implemented by CharacterAccessServer in
 * internal/grpc/characteraccess_service.go. Registered on the core gRPC server
 * (not the plugin proxy) in cmd/holomush/sub_grpc.go, beside
 * SceneAccessService.
 *
 * @generated from service holomush.characteraccess.v1.CharacterAccessService
 */
export const CharacterAccessService: GenService<{
  /**
   * GetCharacterProfile resolves one character's public profile for whichever
   * viewer rung the request's token resolves to, including no token at all.
   * CharacterAccessServer.GetCharacterProfile evaluates profile reachability
   * first and independently; a viewer below that floor receives exactly the
   * response a character id naming no row receives, so a withheld profile
   * cannot be distinguished from a nonexistent one.
   *
   * @generated from rpc holomush.characteraccess.v1.CharacterAccessService.GetCharacterProfile
   */
  getCharacterProfile: {
    methodKind: "unary";
    input: typeof GetCharacterProfileRequestSchema;
    output: typeof GetCharacterProfileResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_holomush_characteraccess_v1_characteraccess, 0);

