// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 HoloMUSH Contributors

// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file holomush/web/v1/web.proto (package holomush.web.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file holomush/web/v1/web.proto.
 */
export const file_holomush_web_v1_web: GenFile = /*@__PURE__*/
  fileDesc("Chlob2xvbXVzaC93ZWIvdjEvd2ViLnByb3RvEg9ob2xvbXVzaC53ZWIudjEiMgoMTG9naW5SZXF1ZXN0EhAKCHVzZXJuYW1lGAEgASgJEhAKCHBhc3N3b3JkGAIgASgJImMKDUxvZ2luUmVzcG9uc2USDwoHc3VjY2VzcxgBIAEoCBISCgpzZXNzaW9uX2lkGAIgASgJEhYKDmNoYXJhY3Rlcl9uYW1lGAMgASgJEhUKDWVycm9yX21lc3NhZ2UYBCABKAkiNgoSU2VuZENvbW1hbmRSZXF1ZXN0EhIKCnNlc3Npb25faWQYASABKAkSDAoEdGV4dBgCIAEoCSJNChNTZW5kQ29tbWFuZFJlc3BvbnNlEg8KB3N1Y2Nlc3MYASABKAgSDgoGb3V0cHV0GAIgASgJEhUKDWVycm9yX21lc3NhZ2UYAyABKAkiKQoTU3RyZWFtRXZlbnRzUmVxdWVzdBISCgpzZXNzaW9uX2lkGAEgASgJIlIKCUdhbWVFdmVudBIMCgR0eXBlGAEgASgJEhYKDmNoYXJhY3Rlcl9uYW1lGAIgASgJEgwKBHRleHQYAyABKAkSEQoJdGltZXN0YW1wGAQgASgDIkEKFFN0cmVhbUV2ZW50c1Jlc3BvbnNlEikKBWV2ZW50GAEgASgLMhouaG9sb211c2gud2ViLnYxLkdhbWVFdmVudCInChFEaXNjb25uZWN0UmVxdWVzdBISCgpzZXNzaW9uX2lkGAEgASgJIhQKEkRpc2Nvbm5lY3RSZXNwb25zZTLkAgoKV2ViU2VydmljZRJGCgVMb2dpbhIdLmhvbG9tdXNoLndlYi52MS5Mb2dpblJlcXVlc3QaHi5ob2xvbXVzaC53ZWIudjEuTG9naW5SZXNwb25zZRJYCgtTZW5kQ29tbWFuZBIjLmhvbG9tdXNoLndlYi52MS5TZW5kQ29tbWFuZFJlcXVlc3QaJC5ob2xvbXVzaC53ZWIudjEuU2VuZENvbW1hbmRSZXNwb25zZRJdCgxTdHJlYW1FdmVudHMSJC5ob2xvbXVzaC53ZWIudjEuU3RyZWFtRXZlbnRzUmVxdWVzdBolLmhvbG9tdXNoLndlYi52MS5TdHJlYW1FdmVudHNSZXNwb25zZTABElUKCkRpc2Nvbm5lY3QSIi5ob2xvbXVzaC53ZWIudjEuRGlzY29ubmVjdFJlcXVlc3QaIy5ob2xvbXVzaC53ZWIudjEuRGlzY29ubmVjdFJlc3BvbnNlQj5aPGdpdGh1Yi5jb20vaG9sb211c2gvaG9sb211c2gvcGtnL3Byb3RvL2hvbG9tdXNoL3dlYi92MTt3ZWJ2MWIGcHJvdG8z");

/**
 * @generated from message holomush.web.v1.LoginRequest
 */
export type LoginRequest = Message<"holomush.web.v1.LoginRequest"> & {
  /**
   * @generated from field: string username = 1;
   */
  username: string;

  /**
   * @generated from field: string password = 2;
   */
  password: string;
};

/**
 * Describes the message holomush.web.v1.LoginRequest.
 * Use `create(LoginRequestSchema)` to create a new message.
 */
export const LoginRequestSchema: GenMessage<LoginRequest> = /*@__PURE__*/
  messageDesc(file_holomush_web_v1_web, 0);

/**
 * @generated from message holomush.web.v1.LoginResponse
 */
export type LoginResponse = Message<"holomush.web.v1.LoginResponse"> & {
  /**
   * @generated from field: bool success = 1;
   */
  success: boolean;

  /**
   * @generated from field: string session_id = 2;
   */
  sessionId: string;

  /**
   * @generated from field: string character_name = 3;
   */
  characterName: string;

  /**
   * @generated from field: string error_message = 4;
   */
  errorMessage: string;
};

/**
 * Describes the message holomush.web.v1.LoginResponse.
 * Use `create(LoginResponseSchema)` to create a new message.
 */
export const LoginResponseSchema: GenMessage<LoginResponse> = /*@__PURE__*/
  messageDesc(file_holomush_web_v1_web, 1);

/**
 * @generated from message holomush.web.v1.SendCommandRequest
 */
export type SendCommandRequest = Message<"holomush.web.v1.SendCommandRequest"> & {
  /**
   * @generated from field: string session_id = 1;
   */
  sessionId: string;

  /**
   * @generated from field: string text = 2;
   */
  text: string;
};

/**
 * Describes the message holomush.web.v1.SendCommandRequest.
 * Use `create(SendCommandRequestSchema)` to create a new message.
 */
export const SendCommandRequestSchema: GenMessage<SendCommandRequest> = /*@__PURE__*/
  messageDesc(file_holomush_web_v1_web, 2);

/**
 * @generated from message holomush.web.v1.SendCommandResponse
 */
export type SendCommandResponse = Message<"holomush.web.v1.SendCommandResponse"> & {
  /**
   * @generated from field: bool success = 1;
   */
  success: boolean;

  /**
   * @generated from field: string output = 2;
   */
  output: string;

  /**
   * @generated from field: string error_message = 3;
   */
  errorMessage: string;
};

/**
 * Describes the message holomush.web.v1.SendCommandResponse.
 * Use `create(SendCommandResponseSchema)` to create a new message.
 */
export const SendCommandResponseSchema: GenMessage<SendCommandResponse> = /*@__PURE__*/
  messageDesc(file_holomush_web_v1_web, 3);

/**
 * @generated from message holomush.web.v1.StreamEventsRequest
 */
export type StreamEventsRequest = Message<"holomush.web.v1.StreamEventsRequest"> & {
  /**
   * @generated from field: string session_id = 1;
   */
  sessionId: string;
};

/**
 * Describes the message holomush.web.v1.StreamEventsRequest.
 * Use `create(StreamEventsRequestSchema)` to create a new message.
 */
export const StreamEventsRequestSchema: GenMessage<StreamEventsRequest> = /*@__PURE__*/
  messageDesc(file_holomush_web_v1_web, 4);

/**
 * @generated from message holomush.web.v1.GameEvent
 */
export type GameEvent = Message<"holomush.web.v1.GameEvent"> & {
  /**
   * @generated from field: string type = 1;
   */
  type: string;

  /**
   * @generated from field: string character_name = 2;
   */
  characterName: string;

  /**
   * @generated from field: string text = 3;
   */
  text: string;

  /**
   * @generated from field: int64 timestamp = 4;
   */
  timestamp: bigint;
};

/**
 * Describes the message holomush.web.v1.GameEvent.
 * Use `create(GameEventSchema)` to create a new message.
 */
export const GameEventSchema: GenMessage<GameEvent> = /*@__PURE__*/
  messageDesc(file_holomush_web_v1_web, 5);

/**
 * @generated from message holomush.web.v1.StreamEventsResponse
 */
export type StreamEventsResponse = Message<"holomush.web.v1.StreamEventsResponse"> & {
  /**
   * @generated from field: holomush.web.v1.GameEvent event = 1;
   */
  event?: GameEvent;
};

/**
 * Describes the message holomush.web.v1.StreamEventsResponse.
 * Use `create(StreamEventsResponseSchema)` to create a new message.
 */
export const StreamEventsResponseSchema: GenMessage<StreamEventsResponse> = /*@__PURE__*/
  messageDesc(file_holomush_web_v1_web, 6);

/**
 * @generated from message holomush.web.v1.DisconnectRequest
 */
export type DisconnectRequest = Message<"holomush.web.v1.DisconnectRequest"> & {
  /**
   * @generated from field: string session_id = 1;
   */
  sessionId: string;
};

/**
 * Describes the message holomush.web.v1.DisconnectRequest.
 * Use `create(DisconnectRequestSchema)` to create a new message.
 */
export const DisconnectRequestSchema: GenMessage<DisconnectRequest> = /*@__PURE__*/
  messageDesc(file_holomush_web_v1_web, 7);

/**
 * @generated from message holomush.web.v1.DisconnectResponse
 */
export type DisconnectResponse = Message<"holomush.web.v1.DisconnectResponse"> & {
};

/**
 * Describes the message holomush.web.v1.DisconnectResponse.
 * Use `create(DisconnectResponseSchema)` to create a new message.
 */
export const DisconnectResponseSchema: GenMessage<DisconnectResponse> = /*@__PURE__*/
  messageDesc(file_holomush_web_v1_web, 8);

/**
 * @generated from service holomush.web.v1.WebService
 */
export const WebService: GenService<{
  /**
   * Authenticate as guest or registered user.
   *
   * @generated from rpc holomush.web.v1.WebService.Login
   */
  login: {
    methodKind: "unary";
    input: typeof LoginRequestSchema;
    output: typeof LoginResponseSchema;
  },
  /**
   * Send a game command (say, pose, quit, etc.)
   *
   * @generated from rpc holomush.web.v1.WebService.SendCommand
   */
  sendCommand: {
    methodKind: "unary";
    input: typeof SendCommandRequestSchema;
    output: typeof SendCommandResponseSchema;
  },
  /**
   * Server-streaming event feed. Client receives game events
   * (say, pose, arrive, leave) as they occur.
   *
   * @generated from rpc holomush.web.v1.WebService.StreamEvents
   */
  streamEvents: {
    methodKind: "server_streaming";
    input: typeof StreamEventsRequestSchema;
    output: typeof StreamEventsResponseSchema;
  },
  /**
   * Disconnect ends the session and triggers cleanup.
   *
   * @generated from rpc holomush.web.v1.WebService.Disconnect
   */
  disconnect: {
    methodKind: "unary";
    input: typeof DisconnectRequestSchema;
    output: typeof DisconnectResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_holomush_web_v1_web, 0);

