# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 HoloMUSH Contributors
server:
  http_listen_port: 3200

distributor:
  receivers:
    otlp:
      protocols:
        grpc:

storage:
  trace:
    backend: local
    local:
      path: /tmp/tempo/blocks
    wal:
      path: /tmp/tempo/wal

compactor:
  compaction:
    block_retention: 1h

overrides:
  defaults:
    global:
      max_traces_per_user: 0
