Policy = ("permit" | "forbid") "(" Target ")" ("when" "{" ConditionBlock "}")? ";" .
Target = PrincipalClause "," ActionClause "," ResourceClause .
PrincipalClause = "principal" ("is" <ident>)? .
ActionClause = "action" ("in" "[" <string> ("," <string>)* "]")? .
ResourceClause = "resource" (("is" <ident>) | (<opeq> <string>))? .
ConditionBlock = Conjunction (<opor> Conjunction)* .
Conjunction = Condition (<opand> Condition)* .
Condition = (<bang> Condition) | ("(" ConditionBlock ")") | IfThenElse | HasCondition | ContainsCondition | LikeCondition | InListCondition | InExprCondition | Comparison | ("true" | "false") .
IfThenElse = "if" Condition "then" Condition "else" Condition .
HasCondition = ("principal" | "resource" | "action" | "env") "has" <ident> (<dot> <ident>)* .
ContainsCondition = ("principal" | "resource" | "action" | "env") (<dot> <ident>)* <dot> <containskw> "(" ListExpr ")" .
ListExpr = "[" Literal ("," Literal)* "]" .
Literal = <string> | <number> | ("true" | "false") .
LikeCondition = Expr "like" <string> .
Expr = AttrRef | Literal .
AttrRef = ("principal" | "resource" | "action" | "env") <dot> <ident> (<dot> <ident>)* .
InListCondition = Expr "in" ListExpr .
InExprCondition = Expr "in" Expr .
Comparison = Expr (<opeq> | <opne> | <opge> | <ople> | <opgt> | <oplt>) Expr .