// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 HoloMUSH Contributors

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: holomush/admin/v1/admin.proto

package adminv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AdminService_Status_FullMethodName          = "/holomush.admin.v1.AdminService/Status"
	AdminService_Authenticate_FullMethodName    = "/holomush.admin.v1.AdminService/Authenticate"
	AdminService_Approve_FullMethodName         = "/holomush.admin.v1.AdminService/Approve"
	AdminService_ResetTOTP_FullMethodName       = "/holomush.admin.v1.AdminService/ResetTOTP"
	AdminService_Rekey_FullMethodName           = "/holomush.admin.v1.AdminService/Rekey"
	AdminService_RekeyResume_FullMethodName     = "/holomush.admin.v1.AdminService/RekeyResume"
	AdminService_RekeyAbort_FullMethodName      = "/holomush.admin.v1.AdminService/RekeyAbort"
	AdminService_RekeyStatus_FullMethodName     = "/holomush.admin.v1.AdminService/RekeyStatus"
	AdminService_RekeyList_FullMethodName       = "/holomush.admin.v1.AdminService/RekeyList"
	AdminService_AdminReadStream_FullMethodName = "/holomush.admin.v1.AdminService/AdminReadStream"
)

// AdminServiceClient is the client API for AdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AdminService is the break-glass operator administration service. It is
// served exclusively over a UNIX domain socket (admin.sock) and is never
// exposed over the network.
type AdminServiceClient interface {
	// Status returns the admin-socket server's liveness state and binary version.
	Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	// Authenticate verifies operator credentials + TOTP and returns a
	// short-lived (10 min) session token for use in Approve and ResetTOTP.
	// Spec §3 wire surface; INV-D1, INV-D2.
	Authenticate(ctx context.Context, in *AuthenticateRequest, opts ...grpc.CallOption) (*AuthenticateResponse, error)
	// Approve is the second-op signoff on a pending admin_approvals row.
	// Spec §3, §6 Approve flow; INV-D5, INV-D6, INV-D7.
	Approve(ctx context.Context, in *ApproveRequest, opts ...grpc.CallOption) (*ApproveResponse, error)
	// ResetTOTP clears a target player's TOTP enrollment and emits a
	// crypto.totp_cleared audit event with cleared_by="admin_reset".
	// Spec §3, §4 reset flow.
	ResetTOTP(ctx context.Context, in *ResetTOTPRequest, opts ...grpc.CallOption) (*ResetTOTPResponse, error)
	// Rekey initiates a full DEK rekey for a context and streams 7-phase
	// orchestrator progress back to the caller. Spec §7; INV-E surface.
	Rekey(ctx context.Context, in *RekeyRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RekeyProgress], error)
	// RekeyResume resumes a paused or interrupted rekey and streams progress.
	// Spec §7; INV-E surface.
	RekeyResume(ctx context.Context, in *RekeyResumeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RekeyProgress], error)
	// RekeyAbort cancels an in-progress rekey operation.
	// Spec §7; INV-E surface.
	RekeyAbort(ctx context.Context, in *RekeyAbortRequest, opts ...grpc.CallOption) (*RekeyAbortResponse, error)
	// RekeyStatus returns the current state of a single rekey operation.
	// Spec §7; INV-E surface.
	RekeyStatus(ctx context.Context, in *RekeyStatusRequest, opts ...grpc.CallOption) (*RekeyStatusResponse, error)
	// RekeyList streams status records for active (and optionally terminal)
	// rekey operations. Spec §7; INV-E surface.
	RekeyList(ctx context.Context, in *RekeyListRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RekeyStatusResponse], error)
	// AdminReadStream is the operator break-glass streaming read RPC.
	// Streams EventFrame payloads (with typed metadata_only + no_plaintext_reason
	// redaction fields) for the requested context(s) and time bounds.
	// Spec sub-epic F §3.2, §3.3; ADR-0017.
	AdminReadStream(ctx context.Context, in *AdminReadStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AdminReadStreamResponse], error)
}

type adminServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminServiceClient(cc grpc.ClientConnInterface) AdminServiceClient {
	return &adminServiceClient{cc}
}

func (c *adminServiceClient) Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, AdminService_Status_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) Authenticate(ctx context.Context, in *AuthenticateRequest, opts ...grpc.CallOption) (*AuthenticateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthenticateResponse)
	err := c.cc.Invoke(ctx, AdminService_Authenticate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) Approve(ctx context.Context, in *ApproveRequest, opts ...grpc.CallOption) (*ApproveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApproveResponse)
	err := c.cc.Invoke(ctx, AdminService_Approve_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) ResetTOTP(ctx context.Context, in *ResetTOTPRequest, opts ...grpc.CallOption) (*ResetTOTPResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResetTOTPResponse)
	err := c.cc.Invoke(ctx, AdminService_ResetTOTP_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) Rekey(ctx context.Context, in *RekeyRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RekeyProgress], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AdminService_ServiceDesc.Streams[0], AdminService_Rekey_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RekeyRequest, RekeyProgress]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AdminService_RekeyClient = grpc.ServerStreamingClient[RekeyProgress]

func (c *adminServiceClient) RekeyResume(ctx context.Context, in *RekeyResumeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RekeyProgress], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AdminService_ServiceDesc.Streams[1], AdminService_RekeyResume_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RekeyResumeRequest, RekeyProgress]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AdminService_RekeyResumeClient = grpc.ServerStreamingClient[RekeyProgress]

func (c *adminServiceClient) RekeyAbort(ctx context.Context, in *RekeyAbortRequest, opts ...grpc.CallOption) (*RekeyAbortResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RekeyAbortResponse)
	err := c.cc.Invoke(ctx, AdminService_RekeyAbort_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) RekeyStatus(ctx context.Context, in *RekeyStatusRequest, opts ...grpc.CallOption) (*RekeyStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RekeyStatusResponse)
	err := c.cc.Invoke(ctx, AdminService_RekeyStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) RekeyList(ctx context.Context, in *RekeyListRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RekeyStatusResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AdminService_ServiceDesc.Streams[2], AdminService_RekeyList_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RekeyListRequest, RekeyStatusResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AdminService_RekeyListClient = grpc.ServerStreamingClient[RekeyStatusResponse]

func (c *adminServiceClient) AdminReadStream(ctx context.Context, in *AdminReadStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AdminReadStreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AdminService_ServiceDesc.Streams[3], AdminService_AdminReadStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AdminReadStreamRequest, AdminReadStreamResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AdminService_AdminReadStreamClient = grpc.ServerStreamingClient[AdminReadStreamResponse]

// AdminServiceServer is the server API for AdminService service.
// All implementations must embed UnimplementedAdminServiceServer
// for forward compatibility.
//
// AdminService is the break-glass operator administration service. It is
// served exclusively over a UNIX domain socket (admin.sock) and is never
// exposed over the network.
type AdminServiceServer interface {
	// Status returns the admin-socket server's liveness state and binary version.
	Status(context.Context, *StatusRequest) (*StatusResponse, error)
	// Authenticate verifies operator credentials + TOTP and returns a
	// short-lived (10 min) session token for use in Approve and ResetTOTP.
	// Spec §3 wire surface; INV-D1, INV-D2.
	Authenticate(context.Context, *AuthenticateRequest) (*AuthenticateResponse, error)
	// Approve is the second-op signoff on a pending admin_approvals row.
	// Spec §3, §6 Approve flow; INV-D5, INV-D6, INV-D7.
	Approve(context.Context, *ApproveRequest) (*ApproveResponse, error)
	// ResetTOTP clears a target player's TOTP enrollment and emits a
	// crypto.totp_cleared audit event with cleared_by="admin_reset".
	// Spec §3, §4 reset flow.
	ResetTOTP(context.Context, *ResetTOTPRequest) (*ResetTOTPResponse, error)
	// Rekey initiates a full DEK rekey for a context and streams 7-phase
	// orchestrator progress back to the caller. Spec §7; INV-E surface.
	Rekey(*RekeyRequest, grpc.ServerStreamingServer[RekeyProgress]) error
	// RekeyResume resumes a paused or interrupted rekey and streams progress.
	// Spec §7; INV-E surface.
	RekeyResume(*RekeyResumeRequest, grpc.ServerStreamingServer[RekeyProgress]) error
	// RekeyAbort cancels an in-progress rekey operation.
	// Spec §7; INV-E surface.
	RekeyAbort(context.Context, *RekeyAbortRequest) (*RekeyAbortResponse, error)
	// RekeyStatus returns the current state of a single rekey operation.
	// Spec §7; INV-E surface.
	RekeyStatus(context.Context, *RekeyStatusRequest) (*RekeyStatusResponse, error)
	// RekeyList streams status records for active (and optionally terminal)
	// rekey operations. Spec §7; INV-E surface.
	RekeyList(*RekeyListRequest, grpc.ServerStreamingServer[RekeyStatusResponse]) error
	// AdminReadStream is the operator break-glass streaming read RPC.
	// Streams EventFrame payloads (with typed metadata_only + no_plaintext_reason
	// redaction fields) for the requested context(s) and time bounds.
	// Spec sub-epic F §3.2, §3.3; ADR-0017.
	AdminReadStream(*AdminReadStreamRequest, grpc.ServerStreamingServer[AdminReadStreamResponse]) error
	mustEmbedUnimplementedAdminServiceServer()
}

// UnimplementedAdminServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAdminServiceServer struct{}

func (UnimplementedAdminServiceServer) Status(context.Context, *StatusRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Status not implemented")
}
func (UnimplementedAdminServiceServer) Authenticate(context.Context, *AuthenticateRequest) (*AuthenticateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Authenticate not implemented")
}
func (UnimplementedAdminServiceServer) Approve(context.Context, *ApproveRequest) (*ApproveResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Approve not implemented")
}
func (UnimplementedAdminServiceServer) ResetTOTP(context.Context, *ResetTOTPRequest) (*ResetTOTPResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResetTOTP not implemented")
}
func (UnimplementedAdminServiceServer) Rekey(*RekeyRequest, grpc.ServerStreamingServer[RekeyProgress]) error {
	return status.Error(codes.Unimplemented, "method Rekey not implemented")
}
func (UnimplementedAdminServiceServer) RekeyResume(*RekeyResumeRequest, grpc.ServerStreamingServer[RekeyProgress]) error {
	return status.Error(codes.Unimplemented, "method RekeyResume not implemented")
}
func (UnimplementedAdminServiceServer) RekeyAbort(context.Context, *RekeyAbortRequest) (*RekeyAbortResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RekeyAbort not implemented")
}
func (UnimplementedAdminServiceServer) RekeyStatus(context.Context, *RekeyStatusRequest) (*RekeyStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RekeyStatus not implemented")
}
func (UnimplementedAdminServiceServer) RekeyList(*RekeyListRequest, grpc.ServerStreamingServer[RekeyStatusResponse]) error {
	return status.Error(codes.Unimplemented, "method RekeyList not implemented")
}
func (UnimplementedAdminServiceServer) AdminReadStream(*AdminReadStreamRequest, grpc.ServerStreamingServer[AdminReadStreamResponse]) error {
	return status.Error(codes.Unimplemented, "method AdminReadStream not implemented")
}
func (UnimplementedAdminServiceServer) mustEmbedUnimplementedAdminServiceServer() {}
func (UnimplementedAdminServiceServer) testEmbeddedByValue()                      {}

// UnsafeAdminServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminServiceServer will
// result in compilation errors.
type UnsafeAdminServiceServer interface {
	mustEmbedUnimplementedAdminServiceServer()
}

func RegisterAdminServiceServer(s grpc.ServiceRegistrar, srv AdminServiceServer) {
	// If the following call panics, it indicates UnimplementedAdminServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AdminService_ServiceDesc, srv)
}

func _AdminService_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_Status_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).Status(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_Authenticate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthenticateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).Authenticate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_Authenticate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).Authenticate(ctx, req.(*AuthenticateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_Approve_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApproveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).Approve(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_Approve_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).Approve(ctx, req.(*ApproveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_ResetTOTP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetTOTPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).ResetTOTP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_ResetTOTP_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).ResetTOTP(ctx, req.(*ResetTOTPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_Rekey_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RekeyRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AdminServiceServer).Rekey(m, &grpc.GenericServerStream[RekeyRequest, RekeyProgress]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AdminService_RekeyServer = grpc.ServerStreamingServer[RekeyProgress]

func _AdminService_RekeyResume_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RekeyResumeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AdminServiceServer).RekeyResume(m, &grpc.GenericServerStream[RekeyResumeRequest, RekeyProgress]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AdminService_RekeyResumeServer = grpc.ServerStreamingServer[RekeyProgress]

func _AdminService_RekeyAbort_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RekeyAbortRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).RekeyAbort(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_RekeyAbort_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).RekeyAbort(ctx, req.(*RekeyAbortRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_RekeyStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RekeyStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).RekeyStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_RekeyStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).RekeyStatus(ctx, req.(*RekeyStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_RekeyList_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RekeyListRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AdminServiceServer).RekeyList(m, &grpc.GenericServerStream[RekeyListRequest, RekeyStatusResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AdminService_RekeyListServer = grpc.ServerStreamingServer[RekeyStatusResponse]

func _AdminService_AdminReadStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(AdminReadStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AdminServiceServer).AdminReadStream(m, &grpc.GenericServerStream[AdminReadStreamRequest, AdminReadStreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AdminService_AdminReadStreamServer = grpc.ServerStreamingServer[AdminReadStreamResponse]

// AdminService_ServiceDesc is the grpc.ServiceDesc for AdminService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdminService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "holomush.admin.v1.AdminService",
	HandlerType: (*AdminServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Status",
			Handler:    _AdminService_Status_Handler,
		},
		{
			MethodName: "Authenticate",
			Handler:    _AdminService_Authenticate_Handler,
		},
		{
			MethodName: "Approve",
			Handler:    _AdminService_Approve_Handler,
		},
		{
			MethodName: "ResetTOTP",
			Handler:    _AdminService_ResetTOTP_Handler,
		},
		{
			MethodName: "RekeyAbort",
			Handler:    _AdminService_RekeyAbort_Handler,
		},
		{
			MethodName: "RekeyStatus",
			Handler:    _AdminService_RekeyStatus_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Rekey",
			Handler:       _AdminService_Rekey_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "RekeyResume",
			Handler:       _AdminService_RekeyResume_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "RekeyList",
			Handler:       _AdminService_RekeyList_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "AdminReadStream",
			Handler:       _AdminService_AdminReadStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "holomush/admin/v1/admin.proto",
}
