// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 HoloMUSH Contributors

// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file holomush/control/v1/control.proto (package holomush.control.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file holomush/control/v1/control.proto.
 */
export const file_holomush_control_v1_control: GenFile = /*@__PURE__*/
  fileDesc("CiFob2xvbXVzaC9jb250cm9sL3YxL2NvbnRyb2wucHJvdG8SE2hvbG9tdXNoLmNvbnRyb2wudjEiIwoPU2h1dGRvd25SZXF1ZXN0EhAKCGdyYWNlZnVsGAEgASgIIiMKEFNodXRkb3duUmVzcG9uc2USDwoHbWVzc2FnZRgBIAEoCSIPCg1TdGF0dXNSZXF1ZXN0IlkKDlN0YXR1c1Jlc3BvbnNlEg8KB3J1bm5pbmcYASABKAgSCwoDcGlkGAIgASgFEhYKDnVwdGltZV9zZWNvbmRzGAMgASgDEhEKCWNvbXBvbmVudBgEIAEoCTK8AQoOQ29udHJvbFNlcnZpY2USVwoIU2h1dGRvd24SJC5ob2xvbXVzaC5jb250cm9sLnYxLlNodXRkb3duUmVxdWVzdBolLmhvbG9tdXNoLmNvbnRyb2wudjEuU2h1dGRvd25SZXNwb25zZRJRCgZTdGF0dXMSIi5ob2xvbXVzaC5jb250cm9sLnYxLlN0YXR1c1JlcXVlc3QaIy5ob2xvbXVzaC5jb250cm9sLnYxLlN0YXR1c1Jlc3BvbnNlQkZaRGdpdGh1Yi5jb20vaG9sb211c2gvaG9sb211c2gvcGtnL3Byb3RvL2hvbG9tdXNoL2NvbnRyb2wvdjE7Y29udHJvbHYxYgZwcm90bzM");

/**
 * ShutdownRequest contains shutdown parameters.
 *
 * @generated from message holomush.control.v1.ShutdownRequest
 */
export type ShutdownRequest = Message<"holomush.control.v1.ShutdownRequest"> & {
  /**
   * If true, perform graceful shutdown allowing in-flight requests to complete.
   *
   * @generated from field: bool graceful = 1;
   */
  graceful: boolean;
};

/**
 * Describes the message holomush.control.v1.ShutdownRequest.
 * Use `create(ShutdownRequestSchema)` to create a new message.
 */
export const ShutdownRequestSchema: GenMessage<ShutdownRequest> = /*@__PURE__*/
  messageDesc(file_holomush_control_v1_control, 0);

/**
 * ShutdownResponse confirms shutdown initiation.
 *
 * @generated from message holomush.control.v1.ShutdownResponse
 */
export type ShutdownResponse = Message<"holomush.control.v1.ShutdownResponse"> & {
  /**
   * Human-readable status message.
   *
   * @generated from field: string message = 1;
   */
  message: string;
};

/**
 * Describes the message holomush.control.v1.ShutdownResponse.
 * Use `create(ShutdownResponseSchema)` to create a new message.
 */
export const ShutdownResponseSchema: GenMessage<ShutdownResponse> = /*@__PURE__*/
  messageDesc(file_holomush_control_v1_control, 1);

/**
 * StatusRequest requests current process status.
 *
 * @generated from message holomush.control.v1.StatusRequest
 */
export type StatusRequest = Message<"holomush.control.v1.StatusRequest"> & {
};

/**
 * Describes the message holomush.control.v1.StatusRequest.
 * Use `create(StatusRequestSchema)` to create a new message.
 */
export const StatusRequestSchema: GenMessage<StatusRequest> = /*@__PURE__*/
  messageDesc(file_holomush_control_v1_control, 2);

/**
 * StatusResponse contains current process status.
 *
 * @generated from message holomush.control.v1.StatusResponse
 */
export type StatusResponse = Message<"holomush.control.v1.StatusResponse"> & {
  /**
   * Whether the process is running.
   *
   * @generated from field: bool running = 1;
   */
  running: boolean;

  /**
   * Process ID.
   *
   * @generated from field: int32 pid = 2;
   */
  pid: number;

  /**
   * Seconds since process started.
   *
   * @generated from field: int64 uptime_seconds = 3;
   */
  uptimeSeconds: bigint;

  /**
   * Component name (e.g., "core" or "gateway").
   *
   * @generated from field: string component = 4;
   */
  component: string;
};

/**
 * Describes the message holomush.control.v1.StatusResponse.
 * Use `create(StatusResponseSchema)` to create a new message.
 */
export const StatusResponseSchema: GenMessage<StatusResponse> = /*@__PURE__*/
  messageDesc(file_holomush_control_v1_control, 3);

/**
 * ControlService provides administrative operations for HoloMUSH processes.
 *
 * @generated from service holomush.control.v1.ControlService
 */
export const ControlService: GenService<{
  /**
   * Shutdown initiates process shutdown.
   *
   * @generated from rpc holomush.control.v1.ControlService.Shutdown
   */
  shutdown: {
    methodKind: "unary";
    input: typeof ShutdownRequestSchema;
    output: typeof ShutdownResponseSchema;
  },
  /**
   * Status returns current process status.
   *
   * @generated from rpc holomush.control.v1.ControlService.Status
   */
  status: {
    methodKind: "unary";
    input: typeof StatusRequestSchema;
    output: typeof StatusResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_holomush_control_v1_control, 0);

