// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 HoloMUSH Contributors

// @generated by protoc-gen-es v2.12.1 with parameter "target=ts"
// @generated from file holomush/adminportal/v1/adminportal.proto (package holomush.adminportal.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_buf_validate_validate } from "../../../buf/validate/validate_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file holomush/adminportal/v1/adminportal.proto.
 */
export const file_holomush_adminportal_v1_adminportal: GenFile = /*@__PURE__*/
  fileDesc("Cilob2xvbXVzaC9hZG1pbnBvcnRhbC92MS9hZG1pbnBvcnRhbC5wcm90bxIXaG9sb211c2guYWRtaW5wb3J0YWwudjEiQQoYQWRtaW5MaXN0U2VjdGlvbnNSZXF1ZXN0EiUKFHBsYXllcl9zZXNzaW9uX3Rva2VuGAEgASgJQge6SARyAhABIlQKGUFkbWluTGlzdFNlY3Rpb25zUmVzcG9uc2USNwoIc2VjdGlvbnMYASADKAsyJS5ob2xvbXVzaC5hZG1pbnBvcnRhbC52MS5BZG1pblNlY3Rpb24iQAoMQWRtaW5TZWN0aW9uEgoKAmlkGAEgASgJEhQKDGRpc3BsYXlfbmFtZRgCIAEoCRIOCgZzdGF0dXMYAyABKAkykAEKEkFkbWluUG9ydGFsU2VydmljZRJ6ChFBZG1pbkxpc3RTZWN0aW9ucxIxLmhvbG9tdXNoLmFkbWlucG9ydGFsLnYxLkFkbWluTGlzdFNlY3Rpb25zUmVxdWVzdBoyLmhvbG9tdXNoLmFkbWlucG9ydGFsLnYxLkFkbWluTGlzdFNlY3Rpb25zUmVzcG9uc2VCTlpMZ2l0aHViLmNvbS9ob2xvbXVzaC9ob2xvbXVzaC9wa2cvcHJvdG8vaG9sb211c2gvYWRtaW5wb3J0YWwvdjE7YWRtaW5wb3J0YWx2MWIGcHJvdG8z", [file_buf_validate_validate]);

/**
 * AdminListSectionsRequest carries only the caller's bearer token, because
 * which sections are listed follows entirely from who is asking.
 *
 * @generated from message holomush.adminportal.v1.AdminListSectionsRequest
 */
export type AdminListSectionsRequest = Message<"holomush.adminportal.v1.AdminListSectionsRequest"> & {
  /**
   * player_session_token is the raw bearer token the gateway lifted from the
   * X-Session-Token header. NewAdminSectionInterceptor reads it through the
   * GetPlayerSessionToken() accessor protoc-gen-go emits for this field and
   * resolves the player through auth.PlayerSessionRepository; there is
   * deliberately no player-id field a caller could point at someone else.
   *
   * @generated from field: string player_session_token = 1;
   */
  playerSessionToken: string;
};

/**
 * Describes the message holomush.adminportal.v1.AdminListSectionsRequest.
 * Use `create(AdminListSectionsRequestSchema)` to create a new message.
 */
export const AdminListSectionsRequestSchema: GenMessage<AdminListSectionsRequest> = /*@__PURE__*/
  messageDesc(file_holomush_adminportal_v1_adminportal, 0);

/**
 * AdminListSectionsResponse is the server-filtered projection the /admin nav
 * renders from. It is the only source for that nav — there is no client-side
 * section registry to drift from it.
 *
 * @generated from message holomush.adminportal.v1.AdminListSectionsResponse
 */
export type AdminListSectionsResponse = Message<"holomush.adminportal.v1.AdminListSectionsResponse"> & {
  /**
   * sections are the entries section.AssertSectionAdmission permitted, in
   * section.All()'s row order. An entry the gate refused is absent; its absence
   * is the only signal, so a refused section cannot be distinguished from one
   * that does not exist.
   *
   * @generated from field: repeated holomush.adminportal.v1.AdminSection sections = 1;
   */
  sections: AdminSection[];
};

/**
 * Describes the message holomush.adminportal.v1.AdminListSectionsResponse.
 * Use `create(AdminListSectionsResponseSchema)` to create a new message.
 */
export const AdminListSectionsResponseSchema: GenMessage<AdminListSectionsResponse> = /*@__PURE__*/
  messageDesc(file_holomush_adminportal_v1_adminportal, 1);

/**
 * AdminSection is one row of the admin section registry
 * (internal/admin/section/registry.go) as the portal renders it.
 *
 * @generated from message holomush.adminportal.v1.AdminSection
 */
export type AdminSection = Message<"holomush.adminportal.v1.AdminSection"> & {
  /**
   * id is the registry entry's section id, verbatim — the same lowercase-ASCII
   * token section.Lookup matches and access.AdminSectionResource derives the
   * `admin_section:` reference from. Matching is exact; there is no case
   * folding anywhere on this path.
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * display_name is the human label the nav draws for this section.
   *
   * @generated from field: string display_name = 2;
   */
  displayName: string;

  /**
   * status is section.Status as a string: exactly "available" or "planned" and
   * nothing else. It is carried as DATA so the nav can render a planned
   * section in its own treatment; it is not an authorization signal, and the
   * handler does not filter on it.
   *
   * @generated from field: string status = 3;
   */
  status: string;
};

/**
 * Describes the message holomush.adminportal.v1.AdminSection.
 * Use `create(AdminSectionSchema)` to create a new message.
 */
export const AdminSectionSchema: GenMessage<AdminSection> = /*@__PURE__*/
  messageDesc(file_holomush_adminportal_v1_adminportal, 2);

/**
 * AdminPortalService is the PLAYER-SESSION admin portal surface: the RPCs the
 * browser's /admin routes reach, gated by `admin_section:` ABAC over the
 * network. Its identity is resolved server-side from the request's
 * player_session_token, and NewAdminSectionInterceptor
 * (internal/grpc/admin_interceptor.go) authorizes every method under this
 * package prefix from a fail-closed method-to-section descriptor table before
 * any handler runs.
 *
 * It is deliberately a DIFFERENT package and a DIFFERENT trust boundary from
 * holomush.admin.v1.AdminService, the break-glass operator control plane. That
 * service is served over a UNIX domain socket by internal/admin/socket/ under
 * AssertOperatorAdmin, never over the core gRPC server, and no RPC declared
 * here is reachable from it or it from here.
 *
 * Implemented by AdminPortalServer in internal/grpc/admin_service.go and
 * registered on the core gRPC server in cmd/holomush/sub_grpc.go.
 *
 * @generated from service holomush.adminportal.v1.AdminPortalService
 */
export const AdminPortalService: GenService<{
  /**
   * AdminListSections enumerates the admin sections the calling player may
   * reach, in the shipped registry's row order.
   *
   * AdminPortalServer.AdminListSections runs DOWNSTREAM of the interceptor's
   * admission check: a caller holding no `admin_section:` access is already
   * refused with PermissionDenied and never reaches the handler, so an empty
   * list means "admitted, but nothing permitted" rather than "not an admin".
   * The per-entry filter is section.AssertSectionAdmission, not
   * AssertSectionAccess, so sections that are registered but not yet
   * implemented are still listed and carry their status as data.
   *
   * @generated from rpc holomush.adminportal.v1.AdminPortalService.AdminListSections
   */
  adminListSections: {
    methodKind: "unary";
    input: typeof AdminListSectionsRequestSchema;
    output: typeof AdminListSectionsResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_holomush_adminportal_v1_adminportal, 0);

