-- SPDX-License-Identifier: Apache-2.0
-- Copyright 2026 HoloMUSH Contributors

-- SUPERSEDED — this script is retired and intentionally contains no runnable SQL.
--
-- It was a hand-run adopt script for the pre-golang-migrate era: it marked
-- version 7 as applied in a `schema_migrations` table so the migrator would skip
-- migrations 1-7. Both the era and the tool are gone. `schema_migrations` is no
-- longer the bookkeeping table; goose records applied versions in
-- `goose_db_version`.
--
-- There is no hand-run adopt path any more, and that is deliberate. Adoption of
-- a pre-goose database happens automatically on the first `holomush migrate up`
-- (including the startup auto-migration): it seeds `goose_db_version` from the
-- old ledger and renames `schema_migrations` to `schema_migrations_pre_goose`,
-- inside one transaction guarded by an advisory lock, refusing outright if the
-- old ledger is marked dirty. A second, hand-run path is exactly the foot-gun
-- that automatic gate exists to remove.
--
-- Running this file does nothing. If you reached it looking for a way to mark
-- migrations as applied, read instead:
--
--   site/src/content/docs/operating/how-to/database.md
--     "First boot after the goose cutover"
--   site/src/content/docs/operating/how-to/sandbox/sandbox-restore.md
--     "Pre-deploy rehearsal: the goose migration cutover"
--
-- The file is kept, rather than deleted, so that anyone following an old link or
-- runbook lands on this explanation instead of a missing path.
