// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 HoloMUSH Contributors

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: holomush/plugin/v1/audit.proto

package pluginv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/holomush/holomush/pkg/proto/holomush/plugin/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// PluginAuditServiceName is the fully-qualified name of the PluginAuditService service.
	PluginAuditServiceName = "holomush.plugin.v1.PluginAuditService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// PluginAuditServiceAuditEventProcedure is the fully-qualified name of the PluginAuditService's
	// AuditEvent RPC.
	PluginAuditServiceAuditEventProcedure = "/holomush.plugin.v1.PluginAuditService/AuditEvent"
	// PluginAuditServiceQueryHistoryProcedure is the fully-qualified name of the PluginAuditService's
	// QueryHistory RPC.
	PluginAuditServiceQueryHistoryProcedure = "/holomush.plugin.v1.PluginAuditService/QueryHistory"
)

// PluginAuditServiceClient is a client for the holomush.plugin.v1.PluginAuditService service.
type PluginAuditServiceClient interface {
	// AuditEvent is the per-message ingestion RPC. The host per-plugin
	// JetStream consumer calls this for every event delivered on subjects
	// declared in the plugin's manifest audit block. The plugin MUST
	// INSERT idempotently (ON CONFLICT DO NOTHING) and return a success
	// response; the host then acks the JetStream message. On error the
	// host does NOT nak — JetStream AckWait + MaxDeliver handle retry
	// with natural backoff. The AuditRow payload is forwarded byte-equal
	// (ciphertext is never decrypted before forwarding, INV-CRYPTO-46).
	AuditEvent(context.Context, *connect.Request[v1.AuditEventRequest]) (*connect.Response[v1.AuditEventResponse], error)
	// QueryHistory streams audit rows for a single subject prefix owned
	// by this plugin. The host's bus.QueryHistory routes the call here
	// when the OwnerMap maps the requested subject to this plugin. The
	// plugin MUST enforce domain-specific authorization against
	// req.Caller before returning any rows (e.g., scene membership for
	// core-scenes). Rows are ordered by id (ULID lex = chronological)
	// in the direction specified by req.Direction; the page is bounded by
	// req.PageSize (host caps at 200; plugin MUST NOT exceed that cap).
	QueryHistory(context.Context, *connect.Request[v1.QueryHistoryRequest]) (*connect.ServerStreamForClient[v1.QueryHistoryResponse], error)
}

// NewPluginAuditServiceClient constructs a client for the holomush.plugin.v1.PluginAuditService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewPluginAuditServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) PluginAuditServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	pluginAuditServiceMethods := v1.File_holomush_plugin_v1_audit_proto.Services().ByName("PluginAuditService").Methods()
	return &pluginAuditServiceClient{
		auditEvent: connect.NewClient[v1.AuditEventRequest, v1.AuditEventResponse](
			httpClient,
			baseURL+PluginAuditServiceAuditEventProcedure,
			connect.WithSchema(pluginAuditServiceMethods.ByName("AuditEvent")),
			connect.WithClientOptions(opts...),
		),
		queryHistory: connect.NewClient[v1.QueryHistoryRequest, v1.QueryHistoryResponse](
			httpClient,
			baseURL+PluginAuditServiceQueryHistoryProcedure,
			connect.WithSchema(pluginAuditServiceMethods.ByName("QueryHistory")),
			connect.WithClientOptions(opts...),
		),
	}
}

// pluginAuditServiceClient implements PluginAuditServiceClient.
type pluginAuditServiceClient struct {
	auditEvent   *connect.Client[v1.AuditEventRequest, v1.AuditEventResponse]
	queryHistory *connect.Client[v1.QueryHistoryRequest, v1.QueryHistoryResponse]
}

// AuditEvent calls holomush.plugin.v1.PluginAuditService.AuditEvent.
func (c *pluginAuditServiceClient) AuditEvent(ctx context.Context, req *connect.Request[v1.AuditEventRequest]) (*connect.Response[v1.AuditEventResponse], error) {
	return c.auditEvent.CallUnary(ctx, req)
}

// QueryHistory calls holomush.plugin.v1.PluginAuditService.QueryHistory.
func (c *pluginAuditServiceClient) QueryHistory(ctx context.Context, req *connect.Request[v1.QueryHistoryRequest]) (*connect.ServerStreamForClient[v1.QueryHistoryResponse], error) {
	return c.queryHistory.CallServerStream(ctx, req)
}

// PluginAuditServiceHandler is an implementation of the holomush.plugin.v1.PluginAuditService
// service.
type PluginAuditServiceHandler interface {
	// AuditEvent is the per-message ingestion RPC. The host per-plugin
	// JetStream consumer calls this for every event delivered on subjects
	// declared in the plugin's manifest audit block. The plugin MUST
	// INSERT idempotently (ON CONFLICT DO NOTHING) and return a success
	// response; the host then acks the JetStream message. On error the
	// host does NOT nak — JetStream AckWait + MaxDeliver handle retry
	// with natural backoff. The AuditRow payload is forwarded byte-equal
	// (ciphertext is never decrypted before forwarding, INV-CRYPTO-46).
	AuditEvent(context.Context, *connect.Request[v1.AuditEventRequest]) (*connect.Response[v1.AuditEventResponse], error)
	// QueryHistory streams audit rows for a single subject prefix owned
	// by this plugin. The host's bus.QueryHistory routes the call here
	// when the OwnerMap maps the requested subject to this plugin. The
	// plugin MUST enforce domain-specific authorization against
	// req.Caller before returning any rows (e.g., scene membership for
	// core-scenes). Rows are ordered by id (ULID lex = chronological)
	// in the direction specified by req.Direction; the page is bounded by
	// req.PageSize (host caps at 200; plugin MUST NOT exceed that cap).
	QueryHistory(context.Context, *connect.Request[v1.QueryHistoryRequest], *connect.ServerStream[v1.QueryHistoryResponse]) error
}

// NewPluginAuditServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewPluginAuditServiceHandler(svc PluginAuditServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	pluginAuditServiceMethods := v1.File_holomush_plugin_v1_audit_proto.Services().ByName("PluginAuditService").Methods()
	pluginAuditServiceAuditEventHandler := connect.NewUnaryHandler(
		PluginAuditServiceAuditEventProcedure,
		svc.AuditEvent,
		connect.WithSchema(pluginAuditServiceMethods.ByName("AuditEvent")),
		connect.WithHandlerOptions(opts...),
	)
	pluginAuditServiceQueryHistoryHandler := connect.NewServerStreamHandler(
		PluginAuditServiceQueryHistoryProcedure,
		svc.QueryHistory,
		connect.WithSchema(pluginAuditServiceMethods.ByName("QueryHistory")),
		connect.WithHandlerOptions(opts...),
	)
	return "/holomush.plugin.v1.PluginAuditService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case PluginAuditServiceAuditEventProcedure:
			pluginAuditServiceAuditEventHandler.ServeHTTP(w, r)
		case PluginAuditServiceQueryHistoryProcedure:
			pluginAuditServiceQueryHistoryHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedPluginAuditServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedPluginAuditServiceHandler struct{}

func (UnimplementedPluginAuditServiceHandler) AuditEvent(context.Context, *connect.Request[v1.AuditEventRequest]) (*connect.Response[v1.AuditEventResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("holomush.plugin.v1.PluginAuditService.AuditEvent is not implemented"))
}

func (UnimplementedPluginAuditServiceHandler) QueryHistory(context.Context, *connect.Request[v1.QueryHistoryRequest], *connect.ServerStream[v1.QueryHistoryResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("holomush.plugin.v1.PluginAuditService.QueryHistory is not implemented"))
}
